import {requireAdmin} from '@/lib/admin/access';
import {sql,withDbRetry} from '@/lib/db';
export const dynamic='force-dynamic';

async function safe<T>(work:()=>Promise<T[]>,fallback:T[]=[]){try{return await withDbRetry(work,1)}catch(e){console.error('N-ATLAS evidence query failed',e);return fallback}}

export default async function NatlasEvidence(){
 await requireAdmin();
 const [modes,validation,asr,sources,failures,recent]=await Promise.all([
  safe(()=>sql`SELECT validation_mode,COUNT(*)::int interactions,COUNT(DISTINCT session_key)::int sessions FROM natlas_validation_interactions GROUP BY validation_mode ORDER BY validation_mode`),
  safe(()=>sql`SELECT COUNT(*)::int interactions,COUNT(DISTINCT session_key)::int sessions,COUNT(DISTINCT user_id)::int users,COALESCE(ROUND(AVG(asr_latency_ms)),0)::int avg_asr_ms,COALESCE(ROUND(AVG(answer_latency_ms)),0)::int avg_answer_ms FROM natlas_validation_interactions WHERE validation_mode='VALIDATION'`),
  safe(()=>sql`SELECT asr_success,COUNT(*)::int n FROM natlas_validation_interactions WHERE validation_mode='VALIDATION' GROUP BY asr_success ORDER BY asr_success DESC`),
  safe(()=>sql`SELECT COALESCE(answer_source,'NONE') answer_source,COUNT(*)::int n FROM natlas_validation_interactions WHERE validation_mode='VALIDATION' GROUP BY COALESCE(answer_source,'NONE') ORDER BY n DESC`),
  safe(()=>sql`SELECT COALESCE(failure_code,'UNSPECIFIED') failure_code,COUNT(*)::int n FROM natlas_validation_interactions WHERE validation_mode='VALIDATION' AND (asr_success=false OR answer_success=false) GROUP BY COALESCE(failure_code,'UNSPECIFIED') ORDER BY n DESC LIMIT 12`),
  safe(()=>sql`SELECT validation_mode,language,class_level,subject,topic,asr_success,asr_latency_ms,answer_source,answer_success,answer_latency_ms,mastery_checked,mastery_success,feedback_rating,failure_code,created_at FROM natlas_validation_interactions ORDER BY created_at DESC LIMIT 50`)
 ]);
 const v:any=validation[0]||{interactions:0,sessions:0,users:0,avg_asr_ms:0,avg_answer_ms:0};
 const asrTotal=asr.reduce((n:number,x:any)=>n+Number(x.n||0),0);
 const asrOk=Number((asr.find((x:any)=>x.asr_success===true)||{}).n||0);
 const successRate=asrTotal?Math.round((asrOk/asrTotal)*100):0;
 return <main className="shell admin-validation"><header className="admin-hero"><div><span className="eyebrow">NAIC · N-ATLAS EVIDENCE</span><h1>Voice-first validation, measured from the working artefact.</h1><p>Official figures below use VALIDATION interactions only. Development and pilot traffic remain visible but cannot inflate the real-user evidence count.</p></div></header>
 <section className="admin-kpis"><div><span>Real interactions</span><strong>{v.interactions}</strong><small>VALIDATION only · minimum target 50</small></div><div><span>Validation sessions</span><strong>{v.sessions}</strong><small>{v.users} authenticated users represented</small></div><div><span>N-ATLAS ASR success</span><strong>{successRate}%</strong><small>{asrOk} of {asrTotal} validation attempts</small></div><div><span>Average ASR latency</span><strong>{v.avg_asr_ms} ms</strong><small>answer avg {v.avg_answer_ms} ms</small></div></section>
 <section className="validation-grid"><article className="admin-panel"><h2>Evidence separation</h2>{modes.length?modes.map((x:any)=><div className="validation-row" key={x.validation_mode}><b>{x.validation_mode}</b><span>{x.interactions} interactions</span><small>{x.sessions} sessions</small></div>):<p>No N-ATLAS evidence recorded yet.</p>}</article><article className="admin-panel"><h2>Answer provenance</h2><p>Shows what actually produced the learner answer; NONE remains visible rather than being disguised as success.</p>{sources.length?sources.map((x:any)=><div className="validation-row" key={x.answer_source}><b>{String(x.answer_source).replaceAll('_',' ')}</b><span>{x.n}</span></div>):<p>No validation answers yet.</p>}</article></section>
 <section className="validation-grid"><article className="admin-panel"><h2>Failure evidence</h2><p>Failures are retained so the validation report can document measured weaknesses and improvements.</p>{failures.length?failures.map((x:any)=><div className="validation-row" key={x.failure_code}><b>{x.failure_code}</b><span>{x.n}</span></div>):<p>No validation failures recorded.</p>}</article><article className="admin-panel"><h2>Evidence integrity</h2><p>No raw audio, learner names, emails, IP addresses, user-agent strings, full transcripts or full tutor answers are stored in this evidence table.</p><div className="validation-row"><b>Official-count rule</b><span>VALIDATION only</span></div><div className="validation-row"><b>Development traffic</b><span>excluded</span></div><div className="validation-row"><b>Pilot traffic</b><span>excluded</span></div></article></section>
 <section className="admin-panel"><h2>Recent N-ATLAS interactions</h2><div className="validation-events">{recent.map((x:any,i:number)=><div key={i}><b>{x.validation_mode} · {x.asr_success?'ASR ✓':'ASR failed'} · {String(x.answer_source||'NONE').replaceAll('_',' ')}</b><span>{new Date(x.created_at).toLocaleString('en-NG')}</span><code>{JSON.stringify({language:x.language,classLevel:x.class_level,subject:x.subject,topic:x.topic,asrLatencyMs:x.asr_latency_ms,answerSuccess:x.answer_success,answerLatencyMs:x.answer_latency_ms,masteryChecked:x.mastery_checked,masterySuccess:x.mastery_success,feedback:x.feedback_rating,failure:x.failure_code})}</code></div>)}</div></section></main>
}