'use client';
import {useEffect,useRef,useState} from 'react';
type Turn={role:'student'|'teacher';text:string};
type Evidence={sessionKey:string;interactionKey:string;asrModel?:string;asrLatencyMs?:number};
const key=(p:string)=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);
function sessionKey(){try{const k='avora:natlas:evidence-session',v=sessionStorage.getItem(k);if(v)return v;const n=key('session');sessionStorage.setItem(k,n);return n}catch{return key('session')}}
function source(d:any){const x=String(d?.knowledgeSource?.type||d?.curriculumSource?.type||'').toUpperCase();if(['AVORA_CURRICULUM','AVORA_CONTEXT','GENERAL_LEARNING','DETERMINISTIC_MATH'].includes(x))return x;if(String(d?.mode||'').startsWith('ai-'))return 'EXTERNAL_AI';return 'NONE'}
export default function GlobalAskAvora({classLevel='JSS1',exam='BECE'}:{classLevel?:string;exam?:string}){
 const [open,setOpen]=useState(false),[ask,setAsk]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[status,setStatus]=useState('');
 const [transcript,setTranscript]=useState(''),[edited,setEdited]=useState(false),[rating,setRating]=useState<number|null>(null),[turns,setTurns]=useState<Turn[]>([]);
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),activeEvidence=useRef<Evidence|null>(null),lastEvidence=useRef<Evidence|null>(null);
 const queueKey='avora:natlas:evidence-queue';
 function queue(payload:any){try{const q=JSON.parse(localStorage.getItem(queueKey)||'[]');const a=Array.isArray(q)?q:[],k=String(payload.interactionKey||'');if(!k){localStorage.setItem(queueKey,JSON.stringify([...a,payload].slice(-100)));return}const prior=a.find((x:any)=>String(x.interactionKey||'')===k);localStorage.setItem(queueKey,JSON.stringify([...a.filter((x:any)=>String(x.interactionKey||'')!==k),prior?{...prior,...payload}:payload].slice(-100)))}catch{}}
 async function evidence(payload:any){try{const r=await fetch('/api/natlas/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw 0}catch{queue(payload)}}
 async function flush(){try{if(!navigator.onLine)return;const q=JSON.parse(localStorage.getItem(queueKey)||'[]');if(!Array.isArray(q)||!q.length)return;const left=[];for(const x of q){try{const r=await fetch('/api/natlas/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});if(!r.ok)left.push(x)}catch{left.push(x)}}localStorage.setItem(queueKey,JSON.stringify(left))}catch{}}
 useEffect(()=>{void flush();const f=()=>void flush();addEventListener('online',f);return()=>removeEventListener('online',f)},[]);
 async function send(question=ask){
  const q=question.trim();if(!q||busy)return;setBusy(true);setAsk('');const recent=[...turns,{role:'student' as const,text:q}].slice(-12);setTurns(recent);const started=Date.now();
  try{const r=await fetch('/api/tutor/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:'General Learning',topic:'Ask AVORA',classLevel,exam,question:q,recent:recent.slice(-8)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AVORA could not answer.');setTurns(x=>[...x,{role:'teacher',text:String(d.reply||'I do not have a reliable answer yet.')}].slice(-12));const e=activeEvidence.current;if(e){void evidence({...e,language:'en-NG',classLevel,subject:'General Learning',topic:'Ask AVORA',asrSuccess:true,answerSource:source(d),answerSuccess:!d.answerUnavailable,answerLatencyMs:Date.now()-started,failureCode:d.answerUnavailable?'ANSWER_UNAVAILABLE':undefined});activeEvidence.current=null}}
  catch(e:any){const ev=activeEvidence.current;if(ev){void evidence({...ev,language:'en-NG',classLevel,subject:'General Learning',topic:'Ask AVORA',asrSuccess:true,answerSource:'NONE',answerSuccess:false,answerLatencyMs:Date.now()-started,failureCode:'TUTOR_REQUEST_FAILED'});activeEvidence.current=null}setTurns(x=>[...x,{role:'teacher',text:e?.message||'AVORA could not answer just now.'}].slice(-12))}
  finally{setBusy(false)}
 }
 function useCorrection(){const q=transcript.trim(),e=lastEvidence.current;if(!q)return;if(e){activeEvidence.current=e;void evidence({...e,language:'en-NG',classLevel,subject:'General Learning',topic:'Ask AVORA',asrSuccess:true,transcriptCorrected:true})}setAsk(q);setEdited(false);setStatus('Transcript corrected. Ask AVORA again using your correction.')}
 function rate(n:number){const e=lastEvidence.current;if(!e)return;setRating(n);void evidence({...e,language:'en-NG',classLevel,subject:'General Learning',topic:'Ask AVORA',asrSuccess:true,feedbackRating:n})}
 async function toggleVoice(){
  if(recording){recorder.current?.stop();return}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setStatus('Voice recording is not supported in this browser.');return}
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:{ideal:1},sampleRate:{ideal:48000},sampleSize:{ideal:16},echoCancellation:{ideal:true},noiseSuppression:{ideal:true},autoGainControl:{ideal:true}}});const type=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x))||'';const r=new MediaRecorder(stream,type?{mimeType:type,audioBitsPerSecond:128000}:{audioBitsPerSecond:128000});chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{setRecording(false);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});if(!blob.size){setStatus('No voice recording was captured. Please try again.');return}setBusy(true);setStatus('N-ATLAS is transcribing your question…');try{const form=new FormData();form.append('audio',blob,'avora-question.webm');const res=await fetch('/api/natlas/asr',{method:'POST',body:form});const d=await res.json().catch(()=>({}));if(!res.ok){const ev={sessionKey:sessionKey(),interactionKey:key('voice-failed'),asrModel:String(d.model||'NCAIR1/NigerianAccentedEnglish'),asrLatencyMs:Number.isFinite(Number(d.latencyMs))?Number(d.latencyMs):undefined};void evidence({...ev,language:'en-NG',classLevel,subject:'General Learning',topic:'Ask AVORA',asrSuccess:false,failureCode:String(d.code||'NATLAS_ASR_ERROR').slice(0,80)});throw new Error(d.error||'N-ATLAS could not transcribe.')}const text=String(d.transcript||'').trim();if(!text)throw new Error('N-ATLAS returned no transcript.');const ev={sessionKey:sessionKey(),interactionKey:key('voice'),asrModel:String(d.model||'NCAIR1/NigerianAccentedEnglish'),asrLatencyMs:Number(d.latencyMs||0)};activeEvidence.current=ev;lastEvidence.current=ev;setTranscript(text);setEdited(false);setRating(null);setAsk(text);void evidence({...ev,language:String(d.language||'en-NG'),classLevel,subject:'General Learning',topic:'Ask AVORA',asrSuccess:true});setStatus('N-ATLAS understood your question. AVORA is preparing an answer…');setBusy(false);await send(text)}catch(e:any){setStatus(e?.message||'N-ATLAS could not transcribe that recording. Please retry.');setBusy(false)}};recorder.current=r;r.start(250);setRecording(true);setStatus('Listening clearly… speak naturally, then tap Stop when you finish.')}catch{setStatus('Microphone permission was not granted. Allow microphone access and try again.')}
 }
 return <div className="global-ask-avora"><button type="button" className="global-ask-trigger" aria-expanded={open} onClick={()=>setOpen(x=>!x)}><span>Ask AVORA</span><small>Text or voice</small></button>{open&&<div className="global-ask-layer" role="dialog" aria-label="Ask AVORA"><header><div><small>ASK AVORA</small><strong>Your AVORA tutor</strong></div><button type="button" aria-label="Close Ask AVORA" onClick={()=>setOpen(false)}>×</button></header><div className="global-ask-conversation">{turns.length?turns.map((t,i)=><div key={i} className={'global-ask-turn '+t.role}><small>{t.role==='student'?'You':'AVORA'}</small><p>{t.text}</p></div>):<div className="global-ask-empty"><b>Ask AVORA just like you do inside a lesson.</b><p>Type a learning question or ask by voice with N-ATLAS.</p></div>}</div>{transcript&&<div className="global-ask-transcript"><small>N-ATLAS heard</small><span>“{transcript}”</span><details><summary>Not what you said?</summary><textarea aria-label="Correct N-ATLAS transcript" value={transcript} onChange={e=>{setTranscript(e.target.value);setEdited(true)}} rows={2}/><button type="button" disabled={!edited||!transcript.trim()} onClick={useCorrection}>Use my correction</button></details>{lastEvidence.current&&<div className="natlas-feedback"><small>Was this voice learning interaction useful?</small><div>{[1,2,3,4,5].map(n=><button key={n} type="button" aria-pressed={rating===n} onClick={()=>rate(n)}>{n}</button>)}</div></div>}</div>}{status&&<p className="global-ask-status" role="status">{status}</p>}<div className="global-ask-compose"><textarea rows={2} value={ask} onChange={e=>setAsk(e.target.value)} placeholder="Ask AVORA anything you are learning…"/><div><button type="button" onClick={toggleVoice} disabled={busy}>{recording?'Stop voice':'🎙 Ask by voice'}</button><button type="button" onClick={()=>send()} disabled={busy||!ask.trim()}>{busy?'Thinking…':'Ask AVORA'}</button></div></div></div>}</div>
}