'use client'; import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>; const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
export default function HCFLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS1 MATHEMATICS · WHOLE NUMBERS</span><h1>Highest Common Factor (HCF)</h1><p>Find common factors, identify the greatest one and know exactly when HCF—not LCM—is required.</p></header><section className="wn-objectives"><h2>NERDC-Aligned Objectives</h2><ul><li>Identify common factors.</li><li>Find HCF by common-factor and prime-factor methods.</li><li>Express whole numbers as products of prime factors.</li><li>Distinguish HCF from LCM.</li><li>Solve quantitative-reasoning problems.</li></ul></section>
<section className="wn-section"><h3>1. Factors and Common Factors</h3><W q="Find the HCF of 18 and 24."><L>Factors of 18: 1, 2, 3, 6, 9, 18.</L><L>Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24.</L><L>Common factors: 1, 2, 3, 6.</L><L strong>HCF = 6</L></W></section>
<section className="wn-section"><h3>2. Prime Factorisation</h3><W q="Express 28 as prime factors."><L>28 = 2 × 14</L><L>14 = 2 × 7</L><L strong>28 = 2² × 7</L></W></section>
<section className="wn-section"><h3>3. Prime-Factor Method</h3><W q="Find HCF of 36 and 48."><L>36 = 2² × 3²</L><L>48 = 2⁴ × 3</L><L>Keep only primes common to both, using the smaller common power.</L><L>HCF = 2² × 3</L><L strong>HCF = 12</L><L>36 ÷ 12 = 3 and 48 ÷ 12 = 4. Check passed.</L></W></section>
<section className="wn-section"><h3>4. Three Numbers</h3><W q="Find HCF of 24, 36 and 60."><L>24 = 2³ × 3</L><L>36 = 2² × 3²</L><L>60 = 2² × 3 × 5</L><L>Common to all: 2² × 3.</L><L strong>HCF = 12</L></W></section>
<section className="wn-section"><h3>5. HCF Versus LCM</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Question</th><th>HCF</th><th>LCM</th></tr></thead><tbody><tr><td>Main idea</td><td>Greatest shared factor</td><td>Lowest shared multiple</td></tr><tr><td>Prime powers</td><td>Common primes, smaller powers</td><td>All needed primes, greatest powers</td></tr><tr><td>Typical clue</td><td>largest equal groups</td><td>next common cycle</td></tr></tbody></table></div></section>
<section className="wn-section"><h3>6. Equal-Grouping Problem</h3><W q="24 red counters and 36 blue counters are shared into the greatest possible number of identical groups with none left. How many groups?"><L>The group count must divide both 24 and 36 exactly.</L><L>HCF(24,36) = 12.</L><L strong>There are 12 groups.</L><L>Each group has 2 red and 3 blue counters.</L></W></section>
<section className="wn-section"><h3>7. Quantitative Reasoning</h3><W q="Complete the prime-factor form of 84 if 28 = 2² × 7 and 84 = 3 × 28."><L>84 = 3 × 28.</L><L>= 3 × 2² × 7.</L><L strong>84 = 2² × 3 × 7</L></W></section>
<section className="wn-section"><h3>8. Common Mistakes</h3><div className="lesson-rule"><span>Factors divide a number; multiples are generated from it.</span><span>HCF must divide every original number exactly.</span><span>Use only common prime factors for HCF.</span><span>Use the smaller shared prime power.</span><span>Read the situation before choosing HCF or LCM.</span></div></section><div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}