'use client';
import React from 'react';
type S={title:string;body:string[];example?:{q:string;steps:string[];answer:string}};
type Lesson={title:string;objectives:string[];sections:S[];mistakes:string[]};
const lessons:Record<string,Lesson>={
"Square Root of Numbers":{title:"Square Root of Numbers",objectives:["Explain what squaring a number means and connect a square to area","Identify perfect squares and distinguish them from non-perfect squares","Find squares of whole numbers and decimals","Explain square root as the inverse of squaring","Find square roots of perfect squares by inspection and by prime-factor method","Estimate the square root of a non-perfect square between consecutive whole numbers","Solve quantitative reasoning and real-life problems involving squares and square roots"],sections:[
{title:"1. Foundation: what does it mean to square a number?",body:["Before using the square-root sign, understand the idea that creates a square. If a square has side length 4 units, it contains 4 rows of 4 unit squares. Its area is 4 × 4 = 16 square units. We write this as 4² = 16.","The small raised 2 is called an exponent or index. It tells us to use the number as a factor twice. Therefore 7² means 7 × 7, not 7 × 2.","This gives a useful picture: squaring a positive number can be understood as finding the area of a square whose side is that number."] ,example:{q:"Find 12² and explain what the notation means.",steps:["12² means that 12 is used as a factor two times.","Write the multiplication explicitly: 12 × 12.","Multiply: 12 × 12 = 144.","Therefore 12² = 144.","Check the meaning: a square of side 12 units would have area 144 square units."],answer:"12² = 144"}},
{title:"2. Perfect squares: build the pattern instead of memorising blindly",body:["A perfect square is a number obtained by multiplying a whole number by itself. Examples are 1, 4, 9, 16 and 25 because they are 1², 2², 3², 4² and 5².","The sequence continues: 6²=36, 7²=49, 8²=64, 9²=81, 10²=100, 11²=121, 12²=144, 13²=169, 14²=196, 15²=225, 16²=256, 17²=289, 18²=324, 19²=361, 20²=400.","Numbers such as 50 and 70 are not perfect squares because no whole number multiplied by itself gives exactly 50 or 70. Knowing neighbouring perfect squares later helps us estimate their square roots."]},
{title:"3. Squaring larger numbers: make every operation visible",body:["When mental multiplication is not immediate, use a known multiplication method. The exponent does not change the multiplication rules."],example:{q:"Find 23².",steps:["23² means 23 × 23.","Split the second 23 into 20 + 3.","23 × 20 = 460.","23 × 3 = 69.","Add the two partial products: 460 + 69 = 529.","Therefore 23² = 529.","Check: 529 is larger than 20²=400 and smaller than 30²=900, so the size is reasonable."],answer:"23² = 529"}},
{title:"4. Decimal squares",body:["Decimals can also be squared. Multiply the number by itself and keep the place value correct. A useful check is size: if a positive number is less than 1, its square is even smaller."],example:{q:"Find 0.6².",steps:["0.6² means 0.6 × 0.6.","Ignoring the decimal points for a moment, 6 × 6 = 36.","There is one decimal place in each factor, so the product has two decimal places.","36 becomes 0.36.","Check: 0.6 is less than 1, so its square 0.36 should also be less than 1."],answer:"0.6² = 0.36"}},
{title:"5. Square root: reverse the squaring process",body:["A square root asks the reverse question. If 9² = 81, then the positive square root of 81 is 9. We write √81 = 9.","The radical symbol √ means square root. At this level, when AVORA writes √81, we mean the principal, non-negative square root.","Do not confuse square root with dividing by 2. √36 is 6 because 6 × 6 = 36; 36 ÷ 2 = 18 answers a completely different question."],example:{q:"Find √169.",steps:["Ask: which positive whole number multiplied by itself gives 169?","Recall nearby perfect squares: 12²=144 and 13²=169.","Since 13 × 13 = 169, 13 is the positive number whose square is 169.","Therefore √169 = 13.","Check by reversing the operation: 13² = 169."],answer:"√169 = 13"}},
{title:"6. Why the prime-factor method works",body:["Inspection is easy for familiar perfect squares, but the curriculum also requires the factor method. First break the number completely into prime factors.","A perfect square contains prime factors in pairs. This happens because squaring duplicates every prime factor in the original number. If 12 = 2² × 3, then 12² = 2⁴ × 3². To undo the square, take one factor from each identical pair."]},
{title:"7. Prime-factor method — no jump in the working",body:["We will not jump from the number straight to its root. Factorise, pair, select one from each pair, multiply, then check."],example:{q:"Find √144 using the prime-factor method.",steps:["Start by breaking 144 into prime factors.","144 ÷ 2 = 72, so write one factor 2.","72 ÷ 2 = 36, so write another factor 2.","36 ÷ 2 = 18, so write another factor 2.","18 ÷ 2 = 9, so write another factor 2.","9 ÷ 3 = 3, and 3 ÷ 3 = 1.","Therefore 144 = 2 × 2 × 2 × 2 × 3 × 3.","Group identical factors into pairs: (2 × 2) × (2 × 2) × (3 × 3).","Square root removes one copy from each pair, so take 2 × 2 × 3.","2 × 2 × 3 = 12.","Check: 12 × 12 = 144."],answer:"√144 = 12"}},
{title:"8. A larger factor-method example",body:["The same method works when several different prime factors occur. Keep the factors arranged so the pairs are visually obvious."],example:{q:"Find √900 using prime factors.",steps:["900 = 9 × 100.","9 = 3 × 3 and 100 = 2 × 2 × 5 × 5.","So 900 = (2 × 2) × (3 × 3) × (5 × 5).","Take one factor from each pair: 2 × 3 × 5.","2 × 3 × 5 = 30.","Check: 30 × 30 = 900."],answer:"√900 = 30"}},
{title:"9. What if the number is not a perfect square?",body:["Not every number has a whole-number square root. For such a number, first find the perfect square immediately below it and the perfect square immediately above it.","Their roots tell us the two consecutive whole numbers between which the required square root lies. This is estimation, not pretending the root is exact."] ,example:{q:"Estimate the position of √50.",steps:["Look for perfect squares around 50.","7² = 49.","8² = 64.","Therefore 49 < 50 < 64.","Taking square roots preserves this positive order: 7 < √50 < 8.","Because 50 is only 1 greater than 49, √50 is only a little greater than 7.","So √50 is between 7 and 8; it is not exactly 7 because 7² is 49."],answer:"7 < √50 < 8"}},
{title:"10. Estimation by testing a decimal",body:["When a decimal estimate is required, test sensible values by squaring them. Each test tells you whether to move the estimate upward or downward."],example:{q:"Estimate √70 to one decimal place.",steps:["8²=64 and 9²=81, so √70 lies between 8 and 9.","Test 8.3: 8.3² = 68.89, which is below 70.","Test 8.4: 8.4² = 70.56, which is above 70.","So √70 lies between 8.3 and 8.4.","70 is closer to 70.56 than to 68.89, so to one decimal place √70 ≈ 8.4."],answer:"√70 ≈ 8.4 to 1 decimal place"}},
{title:"11. Quantitative reasoning: recognise when a square root is needed",body:["A word problem may never say 'take the square root'. Decide from the relationship. If the area of a square is known and the side is unknown, area = side², so finding the side requires the square root."] ,example:{q:"A square classroom floor has area 324 m². Find the length of one side.",steps:["For a square, area = side × side.","Let the side be s metres. Then s² = 324.","To undo squaring, take the positive square root: s = √324.","18 × 18 = 324, so √324 = 18.","A length cannot be negative in this physical problem."],answer:"The side length is 18 m."}},
{title:"12. Multi-step application",body:["Some problems require a square root first and another operation afterward. Do not stop when you have found an intermediate value."],example:{q:"A square field has area 625 m². A fence will go around it. Find the total fence length.",steps:["The field is square, so first find its side from the area.","side = √625 = 25 m because 25 × 25 = 625.","The question asks for fence around the field, which means perimeter.","Perimeter of a square = 4 × side.","Perimeter = 4 × 25 m = 100 m.","Check: four equal sides of 25 m total 100 m."],answer:"100 m of fencing is required."}},
{title:"13. How to choose a method",body:["For a familiar perfect square such as 81 or 144, inspection can be efficient if you can justify it.","When the question specifically asks for the factor method, show the prime factorisation and pairs even if you already know the root.","For a non-perfect square, bracket it between neighbouring perfect squares and estimate if required. For a word problem, first identify the mathematical relationship before choosing the operation."]},
{title:"14. Mastery reasoning",body:["A learner has mastered this topic when they can explain the difference between a square and a square root, identify perfect squares, calculate squares, obtain roots by factor method, estimate non-perfect roots and recognise square-root relationships inside unfamiliar problems.","Every final answer should be checked when practical: square a proposed root and see whether you return to the original number."] ,example:{q:"A learner says √196 = 98 because 196 ÷ 2 = 98. Explain and correct the error.",steps:["The learner has confused square root with halving.","Square root asks for a number which, multiplied by itself, gives 196.","13² = 169, so the root is greater than 13.","14² = 14 × 14 = 196.","Therefore √196 = 14.","Check: 14 × 14 = 196; but 98 × 98 is nowhere near 196."],answer:"√196 = 14"}}
],mistakes:["Do not read a² as a × 2. It means a × a.","Square root does not mean divide by 2.","In the prime-factor method, pair identical prime factors and take one factor from every complete pair.","Do not call a non-perfect square root a whole number merely because it lies near one.","When a word problem asks for perimeter after giving area, finding the side is only an intermediate step.","Always distinguish an exact equality (=) from an estimate (≈)."]},
"Fractions":{title:"Fractions, Ratios, Decimals and Percentages",objectives:["Convert fractions to ratios, decimals and percentages and vice versa","Explain the connection among the four forms","Solve sharing and quantitative aptitude problems"],sections:[
{title:"1. One quantity, four representations",body:["Fraction, ratio, decimal and percentage can describe the same relationship in different forms.","For example, 3/4 = 3:4 = 0.75 = 75%. The meaning changes slightly with context, but the numerical relationship is connected."]},
{title:"2. Fraction to decimal",body:["Divide the numerator by the denominator."],example:{q:"Convert 3/8 to a decimal.",steps:["3/8 means 3 ÷ 8","3.000 ÷ 8 = 0.375"],answer:"3/8 = 0.375"}},
{title:"3. Fraction to percentage",body:["A percentage means 'out of 100'. Convert by multiplying the fraction by 100%."],example:{q:"Convert 7/20 to a percentage.",steps:["7/20 × 100%","100 ÷ 20 = 5","7 × 5% = 35%"],answer:"7/20 = 35%"}},
{title:"4. Decimal and percentage back to fractions",body:["A terminating decimal can be written over its place-value denominator and simplified. A percentage is written over 100 and simplified."],example:{q:"Convert 0.625 to a fraction.",steps:["0.625 = 625/1000","Divide numerator and denominator by 125","625÷125=5; 1000÷125=8"],answer:"0.625 = 5/8"}},
{title:"5. Fraction and ratio",body:["For a part-to-whole fraction a/b, the numerical ratio a:b corresponds to that fraction. But always read the context: a part-to-part ratio is not automatically the same as a part-to-whole fraction."],example:{q:"18 of 30 learners are girls. Express the fraction of girls as a simplified fraction, decimal and percentage.",steps:["Fraction = 18/30 = 3/5","3 ÷ 5 = 0.6","0.6 × 100% = 60%"],answer:"3/5 = 0.6 = 60%"}}
],mistakes:["Do not attach % to a decimal without multiplying by 100.","Simplify fractions after conversion.","Distinguish part-to-part ratio from part-to-whole fraction."]},
"Commercial Arithmetic":{title:"Commercial Arithmetic",objectives:["Solve household and office arithmetic","Prepare and interpret simple budgets and bills","Calculate profit, loss, simple interest, discount and commission"],sections:[
{title:"1. Household and office arithmetic",body:["Commercial arithmetic applies number skills to money decisions: bills, budgets, buying, selling, saving and earning.","A budget compares expected income with planned expenditure. A sound calculation must preserve units and money notation."]},
{title:"2. Profit and loss",body:["Cost price (CP) is what an item costs the seller. Selling price (SP) is what the buyer pays.","If SP > CP, profit = SP − CP. If CP > SP, loss = CP − SP. Profit or loss percentage is measured against cost price."],example:{q:"A trader buys a bag for ₦24,000 and sells it for ₦30,000. Find profit and profit percent.",steps:["Profit = SP − CP = ₦30,000 − ₦24,000 = ₦6,000","Profit % = 6,000/24,000 × 100%","= 1/4 × 100% = 25%"],answer:"Profit = ₦6,000; profit = 25%."}},
{title:"3. Discount",body:["Marked price is the displayed price. Discount is the reduction from marked price. Amount paid = marked price − discount."],example:{q:"A ₦40,000 item has 15% discount. Find the amount paid.",steps:["Discount = 15/100 × ₦40,000 = ₦6,000","Amount paid = ₦40,000 − ₦6,000"],answer:"₦34,000"}},
{title:"4. Simple interest",body:["Simple interest is calculated on the original principal throughout: I = PRT/100 when R is percent per year.","Amount = principal + interest."],example:{q:"Find the simple interest on ₦50,000 at 8% per annum for 3 years.",steps:["I = PRT/100","= 50,000 × 8 × 3 /100","= ₦12,000","Amount = 50,000 + 12,000"],answer:"Interest = ₦12,000; amount = ₦62,000."}},
{title:"5. Commission and household bills",body:["Commission is payment based on a percentage of sales or transactions. Read tariffs carefully in bill questions."],example:{q:"A salesperson earns 5% commission on ₦280,000 sales. Find the commission.",steps:["Commission = 5/100 × 280,000","= 0.05 × 280,000"],answer:"₦14,000"}}
],mistakes:["Profit percentage uses cost price as the base unless stated otherwise.","Discount is not the final price.","Keep rate and time units consistent in interest problems."]},
"Approximation":{title:"Approximation",objectives:["Approximate to required decimal places","Approximate to required significant figures","Choose and justify the correct degree of accuracy","Solve quantitative aptitude problems"],sections:[
{title:"1. What approximation means",body:["Approximation replaces a number with a nearby value that is easier or suitable for the required accuracy. The answer is not exact, so the requested degree of accuracy matters."]},
{title:"2. Decimal places",body:["Decimal places count digits after the decimal point. Keep the required digit, inspect the next digit: 0–4 keep; 5–9 increase the kept digit by 1."],example:{q:"Round 18.3764 to 2 decimal places.",steps:["Two decimal places keeps 18.37 initially","The next digit is 6","6 ≥ 5, so increase the hundredths digit 7 to 8"],answer:"18.38"}},
{title:"3. Significant figures",body:["Significant figures begin at the first non-zero digit. Leading zeros only locate the decimal point and are not significant."],example:{q:"Round 0.006482 to 2 significant figures.",steps:["First significant digit is 6; second is 4","Next digit is 8, so round 4 upward to 5"],answer:"0.0065"}},
{title:"4. Large numbers and carrying",body:["Rounding can change several places when a kept digit becomes 10."],example:{q:"Round 99,650 to 3 significant figures.",steps:["First three significant digits are 9, 9, 6","Next digit is 5, so 996 rounds to 997 at the required place","Replace following places with zeros"],answer:"99,700"}},
{title:"5. Reasonableness",body:["Approximation is useful for checking calculations. Estimate first, then compare the exact result with the estimate."]}],mistakes:["Decimal places and significant figures are not the same.","Leading zeros are not significant.","Do not drop place-value zeros in large rounded numbers."]},
"Multiplication and Division of Directed Numbers":{title:"Multiplication and Division of Directed Numbers",objectives:["Use square/square-root tables","Interpret tables, charts, records and schedules","Multiply and divide positive and negative numbers correctly"],sections:[
{title:"1. Directed numbers",body:["A directed number carries a sign showing direction relative to zero: positive can represent gain, rise or movement one way; negative can represent loss, fall or the opposite direction.","The sign is part of the number."]},
{title:"2. Sign rules for multiplication",body:["Same signs give a positive product. Different signs give a negative product.","Understand the pattern: 3×2=6, 2×2=4, 1×2=2, 0×2=0, (−1)×2=−2. Continuing the pattern explains why negative × positive is negative."],example:{q:"Calculate (−7) × 6 and (−7) × (−6).",steps:["Different signs: (−7)×6 is negative; 7×6=42 → −42","Same signs: (−7)×(−6) is positive; 7×6=42"],answer:"−42 and +42"}},
{title:"3. Sign rules for division",body:["Division reverses multiplication, so the same sign pattern applies: same signs positive; different signs negative."],example:{q:"Evaluate −84 ÷ 12 and −84 ÷ −12.",steps:["84÷12=7","Different signs → −7","Same signs → +7"],answer:"−7 and 7"}},
{title:"4. Tables, charts and schedules",body:["Read headings, units and direction before calculating. A table is evidence; do not invent values not shown."],example:{q:"A temperature changes from −4°C to 8°C. What is the rise?",steps:["Rise = final − initial","= 8 − (−4)","= 8 + 4"],answer:"12°C"}},
{title:"5. Squares and roots from tables",body:["When using a printed/digital square-root table, identify the number, locate the corresponding entry and check the result by squaring approximately. A table is a tool, not a replacement for understanding square and root."]}],mistakes:["Do not apply addition sign rules to multiplication.","A negative sign is not decoration.","Read chart units before using values."]},
"Algebraic Expressions":{title:"Algebraic Expressions",objectives:["Expand expressions","Factorise simple expressions","Use an area/quadratic box to connect expansion and factorisation","Simplify algebraic fractions with monomial denominators","Model and solve word problems"],sections:[
{title:"1. Language of algebra",body:["A term is a number, variable or product separated by + or −. A coefficient multiplies a variable. Like terms have the same variable part and powers.","Expansion removes brackets by multiplication; factorisation reverses expansion by finding common factors."]},
{title:"2. Expand a(b+c)",body:["The outside factor multiplies every term inside the bracket."],example:{q:"Expand 4(3x − 5).",steps:["4×3x = 12x","4×(−5)=−20"],answer:"12x − 20"}},
{title:"3. Expand two binomials",body:["Every term in the first bracket must multiply every term in the second. An area/quadratic box helps make all four products visible."],example:{q:"Expand (x+3)(x+5).",steps:["x×x=x²","x×5=5x","3×x=3x","3×5=15","Combine like terms: 5x+3x=8x"],answer:"x² + 8x + 15"}},
{title:"4. Factorisation",body:["Factorisation asks which factor is common to every term. Divide each term by that common factor to build the bracket."],example:{q:"Factorise 12x² + 18x.",steps:["HCF of 12 and 18 is 6","Both terms contain x","Common factor = 6x","12x²÷6x=2x; 18x÷6x=3"],answer:"6x(2x+3)"}},
{title:"5. Algebraic fractions",body:["Factor numerator and denominator where possible, then cancel factors—not terms joined by addition."],example:{q:"Simplify 12x²y / 18xy².",steps:["12/18 = 2/3","x²/x = x","y/y² = 1/y"],answer:"2x/(3y)"}},
{title:"6. Word modelling",body:["Define the unknown first, translate the words carefully, then simplify."],example:{q:"A rectangle has length (x+4) cm and width x cm. Write its area.",steps:["Area = length × width","= (x+4)x","= x²+4x"],answer:"x² + 4x cm²"}}
],mistakes:["Do not multiply only the first term inside a bracket.","Cancel factors, not added terms.","Combine only like terms."]},
"Simple Equations":{title:"Simple Equations",objectives:["Understand equality as balance","Solve one-variable equations","Check solutions by substitution","Model real-life situations with equations"],sections:[
{title:"1. Equation as a balance",body:["An equation states that two expressions have equal value. Whatever valid operation you perform on one side must be performed on the other to preserve equality."]},
{title:"2. One-step and two-step equations",body:["Undo operations in reverse order while preserving the balance."],example:{q:"Solve 3x − 4 = 17.",steps:["Add 4 to both sides: 3x = 21","Divide both sides by 3: x = 7","Check: 3(7)−4=21−4=17"],answer:"x = 7"}},
{title:"3. Variables on both sides",body:["Collect variable terms on one side and constants on the other using equal operations."],example:{q:"Solve 5x + 2 = 3x + 18.",steps:["Subtract 3x from both sides: 2x+2=18","Subtract 2: 2x=16","Divide by 2: x=8","Check: 42=42"],answer:"x = 8"}},
{title:"4. Equations from words",body:["Choose a variable, translate the relationship, solve, then answer in the original context."],example:{q:"A number is doubled and 5 is added. The result is 23. Find the number.",steps:["Let the number be x","2x+5=23","2x=18","x=9"],answer:"The number is 9."}}
],mistakes:["Do not 'move' terms without understanding the inverse operation.","Always check by substitution.","Define the unknown in word problems."]},
"Linear Inequalities":{title:"Linear Inequalities",objectives:["Identify inequalities in one variable","Solve inequalities","Represent solutions on number lines","Solve inequality word problems"],sections:[
{title:"1. Inequality language",body:["< means less than, > greater than, ≤ less than or equal to, ≥ greater than or equal to. Unlike an equation, an inequality often has many solutions."]},
{title:"2. Solve like an equation—until a negative multiplication/division",body:["Adding or subtracting the same number preserves order. Multiplying or dividing both sides by a negative reverses the inequality sign."],example:{q:"Solve 3x + 2 < 14.",steps:["Subtract 2: 3x < 12","Divide by positive 3: x < 4"],answer:"x < 4"}},
{title:"3. Why the sign reverses",body:["Because −2 < 1, multiplying both by −1 gives 2 > −1. Negative multiplication reflects numbers across zero, reversing order."],example:{q:"Solve −2x ≥ 10.",steps:["Divide both sides by −2","Because the divisor is negative, reverse ≥ to ≤","x ≤ −5","Check x=−6: −2(−6)=12 ≥10"],answer:"x ≤ −5"}},
{title:"4. Number-line representation",body:["Use an open circle for < or > because the boundary is excluded. Use a filled circle for ≤ or ≥ because the boundary is included. Shade/arrow toward all allowed values."]},
{title:"5. Word problem",body:["Translate limit words carefully: 'at most' means ≤; 'at least' means ≥; 'more than' means >; 'less than' means <."],example:{q:"A bus can carry at most 54 people. There are already 38 aboard. If x more enter, form and solve an inequality.",steps:["38+x ≤54","Subtract 38: x≤16"],answer:"At most 16 more people can enter."}}
],mistakes:["Reverse the sign only when multiplying/dividing by a negative.","Open and filled circles have different meanings.","An inequality answer is usually a set/range, not one number."]},
"Graph":{title:"Graphs and the Cartesian Plane",objectives:["Identify x- and y-axes","Plot ordered pairs","Prepare tables of values","Plot and interpret linear equations","Interpret real-life linear graphs"],sections:[
{title:"1. Cartesian plane",body:["The horizontal axis is x; the vertical axis is y. They meet at the origin (0,0). An ordered pair is written (x,y): move along x first, then y."]},
{title:"2. Quadrants and plotting",body:["Signs locate points: (+,+), (−,+), (−,−), (+,−) in quadrants I–IV respectively."],example:{q:"Describe how to plot (−3,2).",steps:["Start at (0,0)","Move 3 units left because x=−3","Move 2 units up because y=2"],answer:"Plot the point at (−3,2), in quadrant II."}},
{title:"3. Table of values",body:["A linear equation links x and y. Choose x-values and calculate corresponding y-values before plotting."],example:{q:"Prepare values for y=2x+1 when x=−1,0,1,2.",steps:["x=−1: y=−2+1=−1","x=0: y=1","x=1: y=3","x=2: y=5"],answer:"Points: (−1,−1),(0,1),(1,3),(2,5)."}},
{title:"4. Plot and interpret a straight line",body:["Choose a consistent scale, label axes and units, plot accurately, then draw the straight line through the points. A point on the line satisfies the equation."]},
{title:"5. Real-life graphs",body:["In a distance-time graph, slope shows rate of change: steeper segments represent greater speed when scales are the same; horizontal distance means no change in distance."],example:{q:"A cyclist travels 30 km in 2 h at constant speed. Find the gradient/rate.",steps:["Rate = change in distance/change in time","=30/2"],answer:"15 km/h"}}
],mistakes:["Coordinates are x first, y second.","Never omit graph scale and units.","Do not join unrelated data blindly; interpret what the line means."]},
"Plane Figure/ Shapes":{title:"Plane Figures, Shapes and Scale Drawing",objectives:["State properties of parallelogram, rhombus and kite","Recognise shapes","Draw to scale","Convert actual and scaled lengths","Solve measurement problems"],sections:[
{title:"1. Properties matter more than appearance",body:["A parallelogram has both pairs of opposite sides parallel and equal; opposite angles are equal and diagonals bisect each other.","A rhombus is a parallelogram with all four sides equal; its diagonals bisect at right angles.","A kite has two pairs of adjacent equal sides; one diagonal is a line of symmetry in the usual kite and the diagonals meet at right angles."]},
{title:"2. Scale drawing",body:["A scale compares drawing length with actual length in the same units. For 1:100, 1 cm on the drawing represents 100 cm in reality."]},
{title:"3. Actual to drawing",body:["Convert units first, then apply the scale."],example:{q:"At scale 1:200, how long should a 10 m wall be on the drawing?",steps:["10 m = 1000 cm","Drawing length = 1000÷200 cm"],answer:"5 cm"}},
{title:"4. Drawing to actual",body:["Multiply drawing length by the scale denominator, then convert to a sensible unit."],example:{q:"On a 1:500 plan, two points are 7.2 cm apart. Find actual distance.",steps:["Actual = 7.2×500 cm = 3600 cm","3600 cm ÷100 =36 m"],answer:"36 m"}},
{title:"5. Measurement problem",body:["A good scale drawing states the scale, uses accurate ruler/protractor work and labels dimensions. Never measure from a diagram declared 'not to scale'."]}],mistakes:["Convert units before applying scale.","A rhombus need not be a square.","Do not classify shapes only by how they look."]},
"Angles":{title:"Angles, Polygons, Elevation and Depression",objectives:["Find angle sums in triangles and quadrilaterals","Find interior-angle sums of polygons","Distinguish elevation and depression","Use scale drawing for distance/height problems","Relate elevation and depression"],sections:[
{title:"1. Triangle and quadrilateral foundations",body:["Angles in any triangle sum to 180°. A quadrilateral can be split into two triangles, so its interior angles sum to 360°."]},
{title:"2. Polygon interior-angle sum",body:["From one vertex, an n-sided convex polygon can be divided into n−2 triangles. Therefore sum of interior angles = (n−2)×180°."],example:{q:"Find the sum of interior angles of a hexagon.",steps:["n=6","(n−2)×180°=(6−2)×180°","=4×180°"],answer:"720°"}},
{title:"3. Missing angle",body:["Use the correct total, then subtract known angles."],example:{q:"Three angles of a quadrilateral are 85°, 110° and 72°. Find the fourth.",steps:["Quadrilateral sum=360°","Known sum=85+110+72=267°","Missing=360−267"],answer:"93°"}},
{title:"4. Elevation and depression",body:["Angle of elevation is measured upward from a horizontal line of sight. Angle of depression is measured downward from a horizontal line of sight.","With parallel horizontal lines, corresponding/alternate angle relationships explain why an angle of depression can equal the corresponding angle of elevation."]},
{title:"5. Scale-drawing application",body:["At JSS2, construct the given angle and scaled distance accurately, complete the right-triangle representation, then measure the requested scaled length and convert back. Do not introduce trigonometric ratios when the curriculum asks for scale drawing."]}],mistakes:["Use (n−2)×180°, not n×180°.","Elevation/depression are measured from horizontal, not vertical.","Respect the stated scale."]},
"Bearing":{title:"Bearing",objectives:["Identify major and minor cardinal points","Locate objects using compass and three-digit bearings","Measure distances using scale drawing"],sections:[
{title:"1. Direction foundation",body:["Major cardinal points are North, East, South and West. Minor/intercardinal points include NE, SE, SW and NW."]},
{title:"2. Three-digit bearings",body:["A three-digit bearing is measured clockwise from North and written with three digits: 045°, 090°, 180°, 270°. Always begin at the north line of the starting point."]},
{title:"3. Compass bearings",body:["Compass notation describes direction from North or South toward East or West, such as N30°E. Keep it distinct from three-digit bearing notation."]},
{title:"4. Locate an object",body:["Draw North at the starting point, place the protractor centre at the point, measure clockwise, draw the bearing ray, then mark the scaled distance."],example:{q:"A clinic is 6 km from a school on bearing 060°. Use scale 1 cm : 2 km. How far is it on the drawing?",steps:["Drawing distance=6÷2 cm=3 cm","Draw North at school","Measure 060° clockwise from North","Draw a 3 cm ray"],answer:"The clinic is marked 3 cm from the school along bearing 060°."}},
{title:"5. Reverse bearing",body:["For two points, the reverse direction differs by 180°. Add 180° if the bearing is below 180°; subtract 180° if it is 180° or more."],example:{q:"If B is on bearing 070° from A, find the bearing of A from B.",steps:["070°<180°, so add 180°","70°+180°=250°"],answer:"250°"}}
],mistakes:["Bearings are measured clockwise from North.","Write three-digit bearings with leading zeros.","A distance needs a scale; a bearing alone gives direction, not distance."]},
"Construction":{title:"Geometrical Construction",objectives:["Construct triangles from sufficient measurements","Construct SSS, SAS and ASA/AAS cases","Bisect an angle accurately","Explain construction arcs"],sections:[
{title:"1. Construction is exact geometry",body:["Use ruler for straight lines, compasses for equal distances/arcs and protractor only where the specified construction permits angle measurement. Keep construction arcs visible because they show why the result is valid."]},
{title:"2. SSS triangle",body:["When all three sides are known, draw one side as base. From each endpoint draw arcs with radii equal to the other two sides. Their intersection fixes the third vertex."],example:{q:"Construct triangle ABC with AB=6 cm, AC=5 cm, BC=4 cm.",steps:["Draw AB=6 cm","Centre A, radius 5 cm: draw an arc","Centre B, radius 4 cm: draw an intersecting arc","Call intersection C","Join AC and BC","Measure sides to check"],answer:"Triangle ABC is fixed by the three side lengths."}},
{title:"3. SAS triangle",body:["Two sides and the included angle determine a triangle: draw one side, construct the included angle at the correct endpoint, mark the second side length, then join the remaining vertices."]},
{title:"4. ASA/AAS triangle",body:["Draw the known side, construct the given angle rays at the required endpoints; their intersection determines the third vertex."]},
{title:"5. Bisect an angle",body:["An angle bisector divides an angle into two equal angles."],example:{q:"Bisect ∠A using ruler and compasses.",steps:["Centre A, draw an arc cutting both arms at P and Q","With equal compass radius, draw arcs from P and Q to intersect at R","Join A to R","AR is the angle bisector because R is equally distant from P and Q"],answer:"∠PAR = ∠RAQ."}}
],mistakes:["Do not erase construction arcs.","Use the included angle in SAS correctly.","A sketch is not a construction."]},
"Data Presentation":{title:"Data Presentation",objectives:["Order data","Construct frequency tables","Read pie charts","Calculate and interpret interquartile range","Construct and compare box plots"],sections:[
{title:"1. Raw data to ordered data",body:["Raw data are observations as collected. Ordering them from least to greatest reveals position and makes quartiles easier to determine."]},
{title:"2. Frequency tables",body:["Frequency tells how many times a value/category occurs. Tally carefully and verify that total frequency equals the number of observations."],example:{q:"For 2,3,2,5,3,2,4 construct frequencies.",steps:["2 occurs 3 times","3 occurs 2 times","4 occurs 1 time","5 occurs 1 time","Total=3+2+1+1=7, matching 7 observations"],answer:"Frequencies: 2→3, 3→2, 4→1, 5→1."}},
{title:"3. Reading pie charts",body:["A full circle is 360°. Sector fraction = sector angle/360 = category frequency/total. Use this relationship in either direction."],example:{q:"A 90° sector represents books in a survey of 80 learners. How many chose books?",steps:["90/360=1/4","1/4×80=20"],answer:"20 learners"}},
{title:"4. Quartiles and IQR",body:["Q1 marks the lower quarter, Q2 is the median, Q3 marks the upper quarter. IQR=Q3−Q1 and measures the spread of the middle 50% of the data.","Use one consistent school convention for locating quartiles and state it when an even-sized data set could be treated differently."],example:{q:"For 2,4,5,7,8,10,12,14 find IQR using median-of-halves.",steps:["Lower half: 2,4,5,7 → Q1=(4+5)/2=4.5","Upper half: 8,10,12,14 → Q3=(10+12)/2=11","IQR=11−4.5"],answer:"IQR = 6.5"}},
{title:"5. Box plots",body:["A box plot uses five-number summary: minimum, Q1, median, Q3, maximum. The box spans Q1 to Q3; the line inside is the median; whiskers extend to minimum and maximum.","Compare medians for centre and IQRs for middle spread. A larger IQR means the middle half is more spread out."]}],mistakes:["Order data before finding quartiles.","IQR is Q3−Q1, not maximum−minimum.","Pie-chart angles must relate to 360°."]},
"Probability":{title:"Probability",objectives:["Discuss chance events","Determine probabilities of simple events","Use experiments with coins/dice","Apply probability to uncertain everyday events"],sections:[
{title:"1. Chance and uncertainty",body:["Probability measures how likely an event is. Probability 0 means impossible; 1 means certain; values between 0 and 1 describe degrees of likelihood."]},
{title:"2. Outcomes and events",body:["The sample space lists all possible outcomes. An event is one or more outcomes of interest. For equally likely outcomes, P(event)=favourable outcomes/total possible outcomes."],example:{q:"A fair die is rolled. Find P(rolling an even number).",steps:["Sample space={1,2,3,4,5,6}: 6 equally likely outcomes","Even outcomes={2,4,6}: 3 favourable outcomes","P(even)=3/6"],answer:"1/2"}},
{title:"3. Coin experiment",body:["Theoretical probability predicts from equally likely outcomes; experimental probability uses observed frequency. With more trials, experimental results often become more stable, but need not equal theory exactly."],example:{q:"A coin gives 27 heads in 50 tosses. Find experimental P(head).",steps:["Experimental probability=observed heads/total tosses","=27/50"],answer:"0.54 or 54%"}},
{title:"4. Complement",body:["An event and 'not the event' together cover all possibilities, so P(not A)=1−P(A)."],example:{q:"If P(rain)=0.3, find P(no rain).",steps:["P(no rain)=1−0.3"],answer:"0.7"}},
{title:"5. Everyday interpretation",body:["Probability supports decisions under uncertainty but does not guarantee a single outcome. A 70% chance does not mean the event must happen.","Use trustworthy data and define the population/time period before drawing real-life conclusions."]}],mistakes:["Probability must lie from 0 to 1 inclusive.","Do not confuse experimental frequency with certainty.","List the sample space before counting favourable outcomes."]}
};
export default function JSS2PremiumMathLesson({topic,onExercise}:{topic:string;onExercise:()=>void}){const l=lessons[topic];if(!l)return null;return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS2 MATHEMATICS · NERDC SEPTEMBER 2025</span><h1>{l.title}</h1><p>Concept-first teaching, fully worked reasoning and curriculum-level application.</p></header><section className="wn-objectives"><h2>Learning Objectives</h2><ul>{l.objectives.map(x=><li key={x}>{x}</li>)}</ul></section>{l.sections.map(s=><section className="wn-section" key={s.title}><h3>{s.title}</h3>{s.body.map((p,i)=><p key={i}>{p}</p>)}{s.example&&<div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{s.example.q}</strong></div><div className="math-stack">{s.example.steps.map((x,i)=><div className="math-line" key={i}>{x}</div>)}<div className="math-line math-result">{s.example.answer}</div></div></div>}</section>)}<section className="wn-section"><h3>Common Mistakes and Misconceptions</h3><div className="lesson-rule">{l.mistakes.map(x=><span key={x}>{x}</span>)}</div></section><section className="wn-section"><h3>Mastery Standard</h3><p>Do not move on because a rule has been memorised. You should be able to explain the idea, complete the method accurately, solve an unfamiliar application and check whether the answer is reasonable.</p></section><div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}
export const jss2PremiumMathTopics=Object.keys(lessons);