'use client';
import React from 'react';
type Ex={q:string;steps:string[];answer:string};
type S={title:string;body:string[];example?:Ex;examples?:Ex[]};
type Lesson={title:string;objectives:string[];sections:S[];mistakes:string[]};
const lessons:Record<string,Lesson>={
"Square Root of Numbers":{title:"Square Root of Numbers",objectives:["Explain what squaring a number means and connect a square to area","Identify perfect squares and distinguish them from non-perfect squares","Find squares of whole numbers and decimals","Explain square root as the inverse of squaring","Find square roots of perfect squares by inspection and by prime-factor method","Estimate the square root of a non-perfect square between consecutive whole numbers","Solve quantitative reasoning and real-life problems involving squares and square roots"],sections:[
{title:"1. Foundation: what does it mean to square a number?",body:["Before using the square-root sign, understand the idea that creates a square. If a square has side length 4 units, it contains 4 rows of 4 unit squares. Its area is 4 × 4 = 16 square units. We write this as 4² = 16.","The small raised 2 is called an exponent or index. It tells us to use the number as a factor twice. Therefore 7² means 7 × 7, not 7 × 2.","This gives a useful picture: squaring a positive number can be understood as finding the area of a square whose side is that number."] ,example:{q:"Find 12² and explain what the notation means.",steps:["12² means that 12 is used as a factor two times.","Write the multiplication explicitly: 12 × 12.","Multiply: 12 × 12 = 144.","Therefore 12² = 144.","Check the meaning: a square of side 12 units would have area 144 square units."],answer:"12² = 144"},examples:[{q:"Find 35².",steps:["35² means 35 × 35.","35 × 30 = 1,050 and 35 × 5 = 175.","1,050 + 175 = 1,225.","Check: the result lies between 30²=900 and 40²=1,600."],answer:"35² = 1,225"},{q:"Find 105².",steps:["105² = 105 × 105.","105 × 100 = 10,500.","105 × 5 = 525.","Add: 10,500 + 525 = 11,025."],answer:"105² = 11,025"}]},
{title:"2. Perfect squares: build the pattern instead of memorising blindly",body:["A perfect square is a number obtained by multiplying a whole number by itself. Examples are 1, 4, 9, 16 and 25 because they are 1², 2², 3², 4² and 5².","The sequence continues: 6²=36, 7²=49, 8²=64, 9²=81, 10²=100, 11²=121, 12²=144, 13²=169, 14²=196, 15²=225, 16²=256, 17²=289, 18²=324, 19²=361, 20²=400.","Numbers such as 50 and 70 are not perfect squares because no whole number multiplied by itself gives exactly 50 or 70. Knowing neighbouring perfect squares later helps us estimate their square roots."]},
{title:"3. Squaring larger numbers: make every operation visible",body:["When mental multiplication is not immediate, use a known multiplication method. The exponent does not change the multiplication rules."],example:{q:"Find 23².",steps:["23² means 23 × 23.","Split the second 23 into 20 + 3.","23 × 20 = 460.","23 × 3 = 69.","Add the two partial products: 460 + 69 = 529.","Therefore 23² = 529.","Check: 529 is larger than 20²=400 and smaller than 30²=900, so the size is reasonable."],answer:"23² = 529"}},
{title:"4. Decimal squares",body:["Decimals can also be squared. Multiply the number by itself and keep the place value correct. A useful check is size: if a positive number is less than 1, its square is even smaller."],example:{q:"Find 0.6².",steps:["0.6² means 0.6 × 0.6.","Ignoring the decimal points for a moment, 6 × 6 = 36.","There is one decimal place in each factor, so the product has two decimal places.","36 becomes 0.36.","Check: 0.6 is less than 1, so its square 0.36 should also be less than 1."],answer:"0.6² = 0.36"},examples:[{q:"Find 1.2².",steps:["1.2² = 1.2 × 1.2.","12 × 12 = 144.","There are two decimal places altogether, so write 1.44.","Check: since 1.2 is greater than 1, its square should be greater than 1."],answer:"1.2² = 1.44"},{q:"Find 0.04².",steps:["0.04 × 0.04 uses 4 × 4 = 16.","There are four decimal places altogether.","Write 0.0016.","Check: squaring a positive number below 1 makes it smaller."],answer:"0.04² = 0.0016"}]},
{title:"5. Square root: reverse the squaring process",body:["A square root asks the reverse question. If 9² = 81, then the positive square root of 81 is 9. We write √81 = 9.","The radical symbol √ means square root. At this level, when AVORA writes √81, we mean the principal, non-negative square root.","Do not confuse square root with dividing by 2. √36 is 6 because 6 × 6 = 36; 36 ÷ 2 = 18 answers a completely different question."],example:{q:"Find √169.",steps:["Ask: which positive whole number multiplied by itself gives 169?","Recall nearby perfect squares: 12²=144 and 13²=169.","Since 13 × 13 = 169, 13 is the positive number whose square is 169.","Therefore √169 = 13.","Check by reversing the operation: 13² = 169."],answer:"√169 = 13"}},
{title:"6. Why the prime-factor method works",body:["Inspection is easy for familiar perfect squares, but the curriculum also requires the factor method. First break the number completely into prime factors.","A perfect square contains prime factors in pairs. This happens because squaring duplicates every prime factor in the original number. If 12 = 2² × 3, then 12² = 2⁴ × 3². To undo the square, take one factor from each identical pair."]},
{title:"7. Prime-factor method — no jump in the working",body:["We will not jump from the number straight to its root. Factorise, pair, select one from each pair, multiply, then check."],example:{q:"Find √144 using the prime-factor method.",steps:["Start by breaking 144 into prime factors.","144 ÷ 2 = 72, so write one factor 2.","72 ÷ 2 = 36, so write another factor 2.","36 ÷ 2 = 18, so write another factor 2.","18 ÷ 2 = 9, so write another factor 2.","9 ÷ 3 = 3, and 3 ÷ 3 = 1.","Therefore 144 = 2 × 2 × 2 × 2 × 3 × 3.","Group identical factors into pairs: (2 × 2) × (2 × 2) × (3 × 3).","Square root removes one copy from each pair, so take 2 × 2 × 3.","2 × 2 × 3 = 12.","Check: 12 × 12 = 144."],answer:"√144 = 12"},examples:[{q:"Find √196 by prime factors.",steps:["196 = 2 × 98 = 2 × 2 × 49 = 2 × 2 × 7 × 7.","Pair identical primes: (2×2)(7×7).","Take one from each pair: 2 × 7 = 14.","Check: 14² = 196."],answer:"√196 = 14"},{q:"Find √576 by prime factors.",steps:["576 = 2×2×2×2×2×2×3×3.","Pair them: (2×2)(2×2)(2×2)(3×3).","Take one from each pair: 2×2×2×3 = 24.","Check: 24² = 576."],answer:"√576 = 24"}]},
{title:"8. A larger factor-method example",body:["The same method works when several different prime factors occur. Keep the factors arranged so the pairs are visually obvious."],example:{q:"Find √900 using prime factors.",steps:["900 = 9 × 100.","9 = 3 × 3 and 100 = 2 × 2 × 5 × 5.","So 900 = (2 × 2) × (3 × 3) × (5 × 5).","Take one factor from each pair: 2 × 3 × 5.","2 × 3 × 5 = 30.","Check: 30 × 30 = 900."],answer:"√900 = 30"}},
{title:"9. What if the number is not a perfect square?",body:["Not every number has a whole-number square root. For such a number, first find the perfect square immediately below it and the perfect square immediately above it.","Their roots tell us the two consecutive whole numbers between which the required square root lies. This is estimation, not pretending the root is exact."] ,example:{q:"Estimate the position of √50.",steps:["Look for perfect squares around 50.","7² = 49.","8² = 64.","Therefore 49 < 50 < 64.","Taking square roots preserves this positive order: 7 < √50 < 8.","Because 50 is only 1 greater than 49, √50 is only a little greater than 7.","So √50 is between 7 and 8; it is not exactly 7 because 7² is 49."],answer:"7 < √50 < 8"},examples:[{q:"Between which integers does √30 lie?",steps:["5²=25 and 6²=36.","25 < 30 < 36.","Therefore 5 < √30 < 6."],answer:"5 < √30 < 6"},{q:"Between which integers does √130 lie?",steps:["11²=121 and 12²=144.","121 < 130 < 144.","Therefore 11 < √130 < 12."],answer:"11 < √130 < 12"}]},
{title:"10. Estimation by testing a decimal",body:["When a decimal estimate is required, test sensible values by squaring them. Each test tells you whether to move the estimate upward or downward."],example:{q:"Estimate √70 to one decimal place.",steps:["8²=64 and 9²=81, so √70 lies between 8 and 9.","Test 8.3: 8.3² = 68.89, which is below 70.","Test 8.4: 8.4² = 70.56, which is above 70.","So √70 lies between 8.3 and 8.4.","70 is closer to 70.56 than to 68.89, so to one decimal place √70 ≈ 8.4."],answer:"√70 ≈ 8.4 to 1 decimal place"}},
{title:"11. Quantitative reasoning: recognise when a square root is needed",body:["A word problem may never say 'take the square root'. Decide from the relationship. If the area of a square is known and the side is unknown, area = side², so finding the side requires the square root."] ,example:{q:"A square classroom floor has area 324 m². Find the length of one side.",steps:["For a square, area = side × side.","Let the side be s metres. Then s² = 324.","To undo squaring, take the positive square root: s = √324.","18 × 18 = 324, so √324 = 18.","A length cannot be negative in this physical problem."],answer:"The side length is 18 m."},examples:[{q:"A square tile has area 441 cm². Find its side.",steps:["For a square, area = side².","side = √441.","21 × 21 = 441."],answer:"Side = 21 cm"},{q:"A square garden has side 16 m. Find its area.",steps:["Here the side is known, so square it rather than taking a square root.","Area = 16² = 16 × 16 = 256."],answer:"Area = 256 m²"}]},
{title:"12. Multi-step application",body:["Some problems require a square root first and another operation afterward. Do not stop when you have found an intermediate value."],example:{q:"A square field has area 625 m². A fence will go around it. Find the total fence length.",steps:["The field is square, so first find its side from the area.","side = √625 = 25 m because 25 × 25 = 625.","The question asks for fence around the field, which means perimeter.","Perimeter of a square = 4 × side.","Perimeter = 4 × 25 m = 100 m.","Check: four equal sides of 25 m total 100 m."],answer:"100 m of fencing is required."}},
{title:"13. How to choose a method",body:["For a familiar perfect square such as 81 or 144, inspection can be efficient if you can justify it.","When the question specifically asks for the factor method, show the prime factorisation and pairs even if you already know the root.","For a non-perfect square, bracket it between neighbouring perfect squares and estimate if required. For a word problem, first identify the mathematical relationship before choosing the operation."]},
{title:"14. Mastery reasoning",body:["A learner has mastered this topic when they can explain the difference between a square and a square root, identify perfect squares, calculate squares, obtain roots by factor method, estimate non-perfect roots and recognise square-root relationships inside unfamiliar problems.","Every final answer should be checked when practical: square a proposed root and see whether you return to the original number."] ,example:{q:"A learner says √196 = 98 because 196 ÷ 2 = 98. Explain and correct the error.",steps:["The learner has confused square root with halving.","Square root asks for a number which, multiplied by itself, gives 196.","13² = 169, so the root is greater than 13.","14² = 14 × 14 = 196.","Therefore √196 = 14.","Check: 14 × 14 = 196; but 98 × 98 is nowhere near 196."],answer:"√196 = 14"}}
],mistakes:["Do not read a² as a × 2. It means a × a.","Square root does not mean divide by 2.","In the prime-factor method, pair identical prime factors and take one factor from every complete pair.","Do not call a non-perfect square root a whole number merely because it lies near one.","When a word problem asks for perimeter after giving area, finding the side is only an intermediate step.","Always distinguish an exact equality (=) from an estimate (≈)."]},
"Fractions":{title:"Fractions, Ratios, Decimals and Percentages",objectives:["Explain a fraction as equal parts of a whole or quantity and identify numerator and denominator","Recognise equivalent fractions and simplify fractions without changing their value","Convert fractions to decimals, percentages and ratios and explain why each conversion works","Convert decimals, percentages and ratios back to fractions where the comparison is valid","Distinguish part-to-whole from part-to-part comparisons","Solve quantitative aptitude and everyday problems involving fractions, ratios, decimals and percentages"],sections:[
{title:"1. Foundation: what is a fraction?",body:["A fraction describes equal parts. If one whole object is divided into 4 equal parts and you take 3 parts, you have three quarters, written 3/4.","The bottom number is the denominator. It tells us how many equal parts make one whole. The top number is the numerator. It tells us how many of those equal parts we are considering.","The word equal is essential. If a shape is cut into four pieces of different sizes, one piece is not automatically one quarter of the whole."],example:{q:"A loaf is cut into 8 equal slices and Tola eats 3. What fraction of the loaf did Tola eat?",steps:["The whole loaf has been divided into 8 equal parts, so the denominator is 8.","Tola ate 3 of those equal parts, so the numerator is 3.","Place the number eaten over the total equal parts: 3/8.","The remaining part would be 5/8 because 3/8 + 5/8 = 8/8 = 1 whole."],answer:"Tola ate 3/8 of the loaf."}},
{title:"2. A fraction is also division",body:["The fraction bar means division. Therefore a/b means a ÷ b, provided b is not zero.","This connection is the bridge from fractions to decimals. We are not using a new unrelated trick when we divide the numerator by the denominator; we are carrying out the division already written in the fraction."],example:{q:"Explain why 3/4 can be written as 0.75.",steps:["3/4 means 3 ÷ 4.","Because 3 is smaller than 4, the answer will be less than 1.","Write 3 as 3.00 so the division can continue into decimal places.","4 goes into 30 seven times: 7 × 4 = 28, leaving 2.","Bring down the next 0: 20 ÷ 4 = 5.","Therefore 3 ÷ 4 = 0.75.","Check: 0.75 × 4 = 3, so the division is correct."],answer:"3/4 = 0.75"}},
{title:"3. Equivalent fractions: same amount, different names",body:["Equivalent fractions look different but represent the same value. Multiplying or dividing the numerator and denominator by the same non-zero number preserves the fraction because we are effectively multiplying or dividing by 1.","For example, 1/2 × 2/2 = 2/4. Since 2/2 = 1, the value has not changed."],example:{q:"Show that 6/8 and 3/4 are equivalent.",steps:["Look for a number that divides both 6 and 8 exactly.","Both are divisible by 2.","6 ÷ 2 = 3.","8 ÷ 2 = 4.","So 6/8 = 3/4.","Check using division: 6 ÷ 8 = 0.75 and 3 ÷ 4 = 0.75."],answer:"6/8 = 3/4"}},
{title:"4. Simplifying a fraction completely",body:["To simplify a fraction, divide numerator and denominator by a common factor. To reach simplest form in one step, divide by their Highest Common Factor (HCF).","A fraction is in simplest form when numerator and denominator have no common factor greater than 1."],example:{q:"Simplify 18/30 completely.",steps:["Find a common factor of 18 and 30. Their HCF is 6.","Divide the numerator by 6: 18 ÷ 6 = 3.","Divide the denominator by the same 6: 30 ÷ 6 = 5.","Therefore 18/30 = 3/5.","Check that 3 and 5 have no common factor greater than 1, so 3/5 is simplest."],answer:"18/30 = 3/5"}},
{title:"5. Fraction to decimal — terminating examples",body:["To convert a fraction to a decimal, divide numerator by denominator. Some divisions end after a finite number of decimal places; these are terminating decimals.","Do not guess the decimal from the appearance of the fraction. Perform the division or create an equivalent fraction with denominator 10, 100, 1000 and so on when convenient."],example:{q:"Convert 7/8 to a decimal.",steps:["The fraction bar means division, so calculate 7 ÷ 8.","7 is smaller than 8, so write 7.000 and place 0 before the decimal point in the answer.","70 ÷ 8 = 8 remainder 6, giving 0.8 so far.","Bring down 0: 60 ÷ 8 = 7 remainder 4, giving 0.87.","Bring down 0: 40 ÷ 8 = 5 exactly.","Therefore 7 ÷ 8 = 0.875.","Check: 0.875 × 8 = 7."],answer:"7/8 = 0.875"},examples:[{q:"Convert 3/5 to a decimal.",steps:["3/5 means 3 ÷ 5.","30 tenths ÷ 5 = 6 tenths.","Therefore 3/5 = 0.6."],answer:"0.6"},{q:"Convert 5/16 to a decimal.",steps:["5/16 means 5 ÷ 16.","500 ÷ 16 = 31 remainder 4, giving 0.31 so far.","40 ÷ 16 = 2 remainder 8; 80 ÷ 16 = 5.","Therefore 5/16 = 0.3125."],answer:"0.3125"}]},
{title:"6. Fraction to percentage — understand 'per hundred'",body:["Percent means 'per hundred' or 'out of 100'. Therefore 35% means 35/100.","To convert a fraction to a percentage, find how many hundredths represent the same value. Multiplying by 100% works because 100% represents one whole: 100/100 = 1, so the value is not being changed."],example:{q:"Convert 7/20 to a percentage.",steps:["We want an equivalent fraction with denominator 100.","Ask: 20 × what number = 100? The answer is 5.","Multiply numerator by the same number: 7 × 5 = 35.","So 7/20 = 35/100.","35 out of 100 means 35%.","Check using the general method: 7/20 × 100% = 35%."],answer:"7/20 = 35%"},examples:[{q:"Convert 3/8 to a percentage.",steps:["3/8 × 100% = 300/8%.","300 ÷ 8 = 37.5.","Therefore 3/8 = 37.5%."],answer:"37.5%"},{q:"Convert 9/4 to a percentage.",steps:["An improper fraction can represent more than one whole.","9/4 × 100% = 225%.","A value greater than 100% is reasonable because 9/4 = 2.25 wholes."],answer:"225%"}]},
{title:"7. Percentage to fraction — reverse the meaning",body:["Because percent means out of 100, write the percentage number over 100, then simplify.","A percentage may be greater than 100. That simply represents more than one whole."],example:{q:"Convert 62.5% to a fraction in simplest form.",steps:["62.5% means 62.5/100.","Remove the decimal by multiplying numerator and denominator by 10: 625/1000.","Find the HCF of 625 and 1000, which is 125.","625 ÷ 125 = 5.","1000 ÷ 125 = 8.","Therefore 62.5% = 5/8.","Check: 5 ÷ 8 = 0.625, and 0.625 × 100% = 62.5%."],answer:"62.5% = 5/8"},examples:[{q:"Convert 45% to a fraction.",steps:["45% = 45/100.","Divide top and bottom by 5: 9/20."],answer:"9/20"},{q:"Convert 140% to a fraction.",steps:["140% = 140/100.","Divide by 20: 7/5.","The improper fraction is expected because 140% is more than one whole."],answer:"7/5"}]},
{title:"8. Decimal to fraction — place value tells the denominator",body:["A terminating decimal can be read as tenths, hundredths, thousandths and so on. That place value gives the denominator before simplification.","For example, 0.4 means four tenths, 0.37 means thirty-seven hundredths and 0.625 means six hundred twenty-five thousandths."],example:{q:"Convert 0.375 to a fraction in simplest form.",steps:["There are three digits after the decimal point, so 0.375 means 375 thousandths.","Write 0.375 = 375/1000.","Both numerator and denominator are divisible by 125.","375 ÷ 125 = 3.","1000 ÷ 125 = 8.","Therefore 0.375 = 3/8.","Check: 3 ÷ 8 = 0.375."],answer:"0.375 = 3/8"},examples:[{q:"Convert 0.06 to a fraction.",steps:["0.06 means 6 hundredths: 6/100.","Divide by 2: 3/50."],answer:"3/50"},{q:"Convert 1.25 to a fraction.",steps:["1.25 = 125/100.","Divide numerator and denominator by 25.","125÷25=5 and 100÷25=4."],answer:"5/4 or 1 1/4"}]},
{title:"9. Percentage and decimal — why the decimal point moves",body:["To change a decimal to a percentage, multiply by 100 because percentage asks how many hundredths the value contains. Multiplying by 100 shifts place values two positions to the left, which appears as the decimal point moving two places right.","To change a percentage to a decimal, divide by 100. Do not memorise 'move the point' without knowing that multiplication or division by 100 is the reason."],example:{q:"Convert 0.086 to a percentage, then convert 125% to a decimal.",steps:["For 0.086, multiply by 100: 0.086 × 100 = 8.6.","Attach the percent sign because the result is now expressed per hundred: 8.6%.","For 125%, remove the percent meaning by dividing by 100: 125 ÷ 100 = 1.25.","Notice that 125% is greater than 100%, so its decimal 1.25 is greater than 1. This is reasonable."],answer:"0.086 = 8.6%; 125% = 1.25"}},
{title:"10. Ratio: what exactly is being compared?",body:["A ratio compares quantities. The order matters: 2:5 means first quantity to second quantity is 2 to 5.","A fraction often describes part of a whole, while a ratio may compare part to part or part to whole. Therefore we must read the words before converting.","If boys:girls = 2:3, then boys/girls = 2/3, but the fraction of the whole class who are boys is 2/(2+3) = 2/5. These are different questions."],example:{q:"A class has boys:girls = 3:5. What fraction of the whole class are boys?",steps:["The ratio says 3 equal parts are boys and 5 equal parts are girls.","The whole class therefore contains 3 + 5 = 8 equal ratio parts.","Boys occupy 3 of those 8 total parts.","So the fraction of the whole class who are boys is 3/8.","Do not answer 3/5: that compares boys directly with girls, not boys with the whole class."],answer:"Boys are 3/8 of the class."}},
{title:"11. Fraction to ratio — state the comparison",body:["A fraction a/b can be written numerically as a:b when it is explicitly comparing the first quantity with the second quantity. But context determines whether b is another part or the whole.","When a fraction describes 'part of a whole', a useful part-to-part ratio may require finding the remaining part first."],example:{q:"3/7 of a group are prefects. Find the ratio of prefects to non-prefects.",steps:["The whole group is represented by 7 equal parts.","Prefects occupy 3 parts.","Non-prefects occupy the remaining 7 − 3 = 4 parts.","Therefore prefects : non-prefects = 3 : 4.","Notice that 3:7 would be prefects : whole group, not prefects : non-prefects."],answer:"3:4"}},
{title:"12. Ratio to fraction and percentage of a whole",body:["When a ratio gives two or more parts of one whole, add the ratio parts first to find the total number of equal shares. Then place the required part over that total.","Once the fraction of the whole is known, the same quantity can be converted to a decimal or percentage."],example:{q:"Red:blue counters = 2:3. What percentage of all the counters are blue?",steps:["Red uses 2 ratio parts and blue uses 3 ratio parts.","Total parts = 2 + 3 = 5.","Blue therefore represents 3/5 of the whole.","Convert 3/5 to a decimal: 3 ÷ 5 = 0.6.","Convert to percentage: 0.6 × 100% = 60%."],answer:"60% of the counters are blue."}},
{title:"13. Sharing a quantity in a ratio",body:["To share a total in a ratio, add the ratio terms to find the number of equal shares. Divide the total by that number to find the value of one share, then multiply by each ratio term.","Always check that the final shares add back to the original total."],example:{q:"Share ₦4,200 in the ratio 2:5.",steps:["Add the ratio parts: 2 + 5 = 7 parts.","The ₦4,200 is divided into 7 equal shares.","Value of one share = ₦4,200 ÷ 7 = ₦600.","First share = 2 × ₦600 = ₦1,200.","Second share = 5 × ₦600 = ₦3,000.","Check: ₦1,200 + ₦3,000 = ₦4,200, the original total."],answer:"₦1,200 and ₦3,000"},examples:[{q:"Share 96 in the ratio 5:3.",steps:["Total ratio parts = 5+3=8.","One part = 96÷8=12.","Shares: 5×12=60 and 3×12=36.","Check: 60+36=96."],answer:"60 and 36"},{q:"Share ₦18,000 in the ratio 2:3:4.",steps:["Total parts = 2+3+4=9.","One part = ₦18,000÷9=₦2,000.","Shares are ₦4,000, ₦6,000 and ₦8,000.","Check total = ₦18,000."],answer:"₦4,000, ₦6,000 and ₦8,000"}]},
{title:"14. Finding a percentage of a quantity",body:["A percentage is a fraction of 100, so p% of a quantity means p/100 multiplied by that quantity.","The word 'of' signals multiplication here. Simplify before multiplying when that makes the arithmetic clearer."],example:{q:"Find 35% of 240.",steps:["35% means 35/100.","So 35% of 240 = 35/100 × 240.","Simplify 240/100 to 12/5, or divide 240 by 100 first: 240 ÷ 100 = 2.4.","2.4 × 35 = 84.","Alternative check: 30% of 240 = 72 and 5% = 12; 72 + 12 = 84."],answer:"35% of 240 = 84"},examples:[{q:"Find 12.5% of 320.",steps:["12.5% = 1/8.","320÷8=40."],answer:"40"},{q:"Find 7.5% of ₦48,000.",steps:["7.5%=7.5/100=0.075.","0.075×48,000=3,600."],answer:"₦3,600"}]},
{title:"15. Finding the whole when a fraction or percentage is known",body:["Sometimes the problem gives a part and asks for the whole. Do not multiply by the percentage again. Build an equation showing that the stated fraction or percentage of the whole equals the known part.","This reverse reasoning is important in quantitative aptitude."],example:{q:"30% of a number is 24. Find the number.",steps:["Let the whole number be x.","30% means 30/100 = 0.30.","The statement becomes 0.30 × x = 24.","To undo multiplication by 0.30, divide both sides by 0.30.","x = 24 ÷ 0.30 = 80.","Check: 30% of 80 = 0.30 × 80 = 24."],answer:"The number is 80."},examples:[{q:"15% of a number is 54. Find the number.",steps:["Let the number be x.","0.15x=54.","x=54÷0.15=360.","Check: 15% of 360=54."],answer:"360"},{q:"3/7 of a quantity is 24. Find the whole quantity.",steps:["3/7 × x = 24.","One seventh is 24÷3=8.","Seven sevenths = 8×7=56."],answer:"56"}]},
{title:"16. Percentage increase and decrease",body:["A percentage change is measured against the original quantity unless the question states another base. First find the actual change, then compare that change with the original.","After finding a percentage increase or decrease, distinguish the amount of change from the new final value."],example:{q:"A quantity rises from 40 to 50. Find the percentage increase.",steps:["Original quantity = 40.","New quantity = 50.","Increase = 50 − 40 = 10.","Compare the increase with the original: 10/40.","Convert to percentage: 10/40 × 100% = 25%.","Check: 25% of 40 = 10, and 40 + 10 = 50."],answer:"The percentage increase is 25%."},examples:[{q:"A price falls from ₦8,000 to ₦6,800. Find the percentage decrease.",steps:["Decrease = ₦8,000−₦6,800=₦1,200.","Compare with the original price: 1,200/8,000×100%.","=15%."],answer:"15% decrease"},{q:"Increase ₦12,000 by 18%.",steps:["18% of ₦12,000 = ₦2,160.","New amount = ₦12,000+₦2,160.","Alternatively multiply by 1.18."],answer:"₦14,160"},{q:"Decrease 450 by 12%.",steps:["12% of 450=54.","New value=450−54=396.","Equivalent multiplier: 0.88×450=396."],answer:"396"},{q:"After a 20% increase, a price is ₦9,600. Find the original price.",steps:["After a 20% increase, the new price is 120% of the original.","Let original=x: 1.20x=9,600.","x=9,600÷1.20=8,000."],answer:"₦8,000"},{q:"A value increases by 20% and then decreases by 20%. Does it return to its original value?",steps:["Use 100 as an easy original value.","Increase 20%: 100→120.","Decrease 20% of the new 120: 20%×120=24.","120−24=96.","The two percentages use different bases, so they do not cancel."],answer:"No. It ends at 96, which is 4% below the original."}]},
{title:"17. Mixed quantitative reasoning — choose the representation that helps",body:["Fractions, ratios, decimals and percentages are not four disconnected topics. They are different ways to express relationships. In a problem, convert to the form that makes the required reasoning clearest.","Before calculating, ask: What is the whole? What is the part? What two quantities are being compared? Is the question asking for a share, a percentage, a decimal or a ratio?"],example:{q:"In a club of 80 learners, 3/8 are in the science group. Of the remaining learners, boys:girls = 2:3. How many girls are among the remaining learners?",steps:["First find the science group: 3/8 of 80.","80 ÷ 8 = 10, then 10 × 3 = 30 learners in the science group.","Remaining learners = 80 − 30 = 50.","Among the remaining learners, boys:girls = 2:3.","Total ratio parts = 2 + 3 = 5.","One ratio part = 50 ÷ 5 = 10.","Girls occupy 3 parts, so girls = 3 × 10 = 30.","Check: boys would be 20; 20 + 30 = 50 remaining learners."],answer:"30 girls"}},
{title:"18. Mastery: prove that the forms agree",body:["A strong learner should be able to travel in both directions: fraction ↔ decimal, fraction ↔ percentage, percentage ↔ decimal, and ratio ↔ fraction when the comparison is clearly defined.","Do not accept an answer merely because it looks familiar. Verify it by converting through another representation or checking against the original quantities."],example:{q:"A learner says 3/5 = 0.6 = 6% = 3:5. Identify the error and correct the chain.",steps:["Check the fraction-to-decimal step: 3 ÷ 5 = 0.6, so that part is correct.","Convert 0.6 to a percentage by multiplying by 100: 0.6 × 100% = 60%.","Therefore 6% is wrong; 6% would equal 0.06.","For a direct first-to-second numerical comparison, 3/5 corresponds to 3:5.","The corrected chain is 3/5 = 0.6 = 60%, with 3:5 representing the stated first-to-second ratio."],answer:"Corrected: 3/5 = 0.6 = 60%; direct ratio 3:5."}}
],mistakes:["Do not treat unequal pieces as fractions of equal size.","Do not change only the numerator or only the denominator when making an equivalent fraction.","The fraction bar means division; do not invent a decimal from the digits.","Percent means per hundred. 0.6 is 60%, not 6%.","Always simplify a fraction when simplest form is required.","A part-to-part ratio such as boys:girls = 3:5 does not mean boys are 3/5 of the whole class; the whole has 8 ratio parts.","When sharing in a ratio, add the ratio parts before dividing the total.","Percentage change is normally compared with the original quantity, not the new quantity.","Distinguish the amount of a percentage change from the final amount after the change.","Check conversions by moving through another form or substituting back into the original problem."]},
"Commercial Arithmetic":{title:"Commercial Arithmetic",objectives:["Use arithmetic confidently in household, office and market situations","Interpret bills, receipts, budgets and simple financial records","Distinguish cost price, selling price, marked price, profit and loss","Calculate profit and loss amounts and percentages","Calculate discounts and final prices in direct and reverse problems","Calculate simple interest, principal, rate, time and total amount","Calculate commission and solve multi-step commercial problems"],sections:[
{title:"1. Why commercial arithmetic matters",body:["Commercial arithmetic is ordinary mathematics applied to money decisions in homes, offices and markets. The difficulty is often not multiplication itself but deciding what each number means and which quantity is the correct base.","Before calculating, identify the quantities, their units and the question being asked. Money answers should carry the correct currency symbol and should be checked for reasonableness."],examples:[{q:"A family receives ₦185,000 in a month and plans expenses of ₦42,000, ₦55,000, ₦28,000 and ₦36,000. Find the balance.",steps:["Total planned expenditure = 42,000+55,000+28,000+36,000 = ₦161,000.","Balance = income−expenditure = ₦185,000−₦161,000 = ₦24,000.","Because expenditure is below income, this is a surplus, not a deficit."],answer:"Balance = ₦24,000 surplus"},{q:"An office has ₦96,500 available but its planned expenses total ₦104,200. Find the deficit.",steps:["Deficit means planned expenditure exceeds available money.","Deficit = ₦104,200−₦96,500 = ₦7,700."],answer:"Deficit = ₦7,700"}]},
{title:"2. Bills and household arithmetic",body:["A bill records amounts owed for goods or services. Some bills use quantity × unit price; others combine fixed charges and usage charges. Read the structure before adding.","Always distinguish a subtotal from the final total when another charge or reduction still has to be applied."],examples:[{q:"A household buys 6 units of an item at ₦1,250 each and 4 units at ₦850 each. Find the total bill.",steps:["First item: 6×₦1,250=₦7,500.","Second item: 4×₦850=₦3,400.","Total bill=₦7,500+₦3,400=₦10,900."],answer:"₦10,900"},{q:"An electricity bill has a fixed charge of ₦1,500 plus ₦68 for each of 120 units used. Find the bill.",steps:["Usage charge=120×₦68=₦8,160.","Add fixed charge: ₦8,160+₦1,500=₦9,660."],answer:"₦9,660"}]},
{title:"3. Cost price, selling price, profit and loss",body:["Cost price (CP) is what the seller paid or spent to obtain an item. Selling price (SP) is the amount received when it is sold.","If SP>CP, profit=SP−CP. If CP>SP, loss=CP−SP. First decide whether there is profit or loss before using a formula."],examples:[{q:"A trader buys a bag for ₦24,000 and sells it for ₦30,000. Find the profit.",steps:["SP is greater than CP, so there is a profit.","Profit=SP−CP=₦30,000−₦24,000=₦6,000."],answer:"Profit = ₦6,000"},{q:"A phone bought for ₦85,000 is sold for ₦76,500. Find the loss.",steps:["CP is greater than SP, so there is a loss.","Loss=CP−SP=₦85,000−₦76,500=₦8,500."],answer:"Loss = ₦8,500"}]},
{title:"4. Profit and loss percentages — choose the correct base",body:["At this level, profit percentage and loss percentage are normally measured against cost price because the gain or loss is being compared with the seller's original investment.","Profit%=profit/CP×100%. Loss%=loss/CP×100%. Do not divide by selling price unless a question explicitly defines another comparison."],examples:[{q:"An article costs ₦24,000 and sells for ₦30,000. Find profit percent.",steps:["Profit=₦30,000−₦24,000=₦6,000.","Profit%=6,000/24,000×100%.","6,000/24,000=1/4.","1/4×100%=25%."],answer:"25% profit"},{q:"A trader buys goods for ₦50,000 and sells them for ₦42,500. Find loss percent.",steps:["Loss=₦50,000−₦42,500=₦7,500.","Loss%=7,500/50,000×100%=15%."],answer:"15% loss"},{q:"An item costs ₦8,400 and yields ₦1,260 profit. Find the profit percentage.",steps:["The profit amount is already given.","Profit%=1,260/8,400×100%.","1,260÷8,400=0.15."],answer:"15% profit"}]},
{title:"5. Finding selling price from a profit or loss percentage",body:["When CP and a percentage are known, first find the profit/loss amount or use a multiplier. At p% profit, SP=(100+p)% of CP. At p% loss, SP=(100−p)% of CP.","The multiplier method is efficient, but AVORA first establishes why it works."],examples:[{q:"A bicycle costs ₦64,000. Find the selling price for a 25% profit.",steps:["25% of ₦64,000=₦16,000.","SP=CP+profit=₦64,000+₦16,000=₦80,000.","Equivalent: SP=125%×₦64,000=1.25×₦64,000."],answer:"₦80,000"},{q:"A machine costs ₦150,000 and is sold at 12% loss. Find SP.",steps:["Loss=12% of ₦150,000=₦18,000.","SP=₦150,000−₦18,000=₦132,000.","Check using 88% of CP: 0.88×150,000=132,000."],answer:"₦132,000"}]},
{title:"6. Reverse profit and loss problems",body:["If selling price is known after a percentage profit or loss, the selling price represents a percentage of the original cost price. Do not simply subtract the stated percentage from SP.","At 20% profit, SP=120% of CP. At 15% loss, SP=85% of CP."],examples:[{q:"An item is sold for ₦72,000 at 20% profit. Find its cost price.",steps:["At 20% profit, SP=120% of CP.","So 1.20×CP=₦72,000.","CP=₦72,000÷1.20=₦60,000.","Check: 20% of 60,000=12,000; 60,000+12,000=72,000."],answer:"CP = ₦60,000"},{q:"An item is sold for ₦51,000 at a 15% loss. Find CP.",steps:["At 15% loss, SP=85% of CP.","0.85×CP=₦51,000.","CP=₦51,000÷0.85=₦60,000.","Check: 15% of 60,000=9,000; 60,000−9,000=51,000."],answer:"CP = ₦60,000"}]},
{title:"7. Marked price, discount and amount paid",body:["Marked price (MP) is the displayed price before a discount. Discount is the reduction. Amount paid=MP−discount.","Discount%=discount/MP×100%. A 15% discount means the buyer pays 85% of the marked price."],examples:[{q:"A ₦40,000 item has a 15% discount. Find the discount and amount paid.",steps:["Discount=15/100×₦40,000=₦6,000.","Amount paid=₦40,000−₦6,000=₦34,000."],answer:"Discount ₦6,000; amount paid ₦34,000"},{q:"A shirt marked ₦18,000 is sold for ₦15,300. Find the discount percentage.",steps:["Discount=₦18,000−₦15,300=₦2,700.","Discount%=2,700/18,000×100%=15%."],answer:"15% discount"},{q:"After a 20% discount, a customer pays ₦28,000. Find the marked price.",steps:["After 20% discount, the customer pays 80% of MP.","0.80×MP=₦28,000.","MP=₦28,000÷0.80=₦35,000."],answer:"Marked price = ₦35,000"}]},
{title:"8. Simple interest — understand the quantities",body:["Principal (P) is the original money invested or borrowed. Rate (R) is the percentage charged or earned per time period. Time (T) is how long the money remains invested or borrowed.","For a yearly percentage rate, simple interest I=PRT/100 when T is in years. Simple interest is always calculated on the original principal, not on an increasing balance."],examples:[{q:"Find simple interest on ₦50,000 at 8% per annum for 3 years.",steps:["P=₦50,000, R=8, T=3.","I=PRT/100.","I=50,000×8×3/100=₦12,000.","Amount=P+I=₦62,000."],answer:"Interest ₦12,000; amount ₦62,000"},{q:"Find the simple interest on ₦120,000 at 7.5% per annum for 2 years.",steps:["I=120,000×7.5×2/100.","7.5×2=15, so this is 15% of ₦120,000.","I=₦18,000."],answer:"₦18,000"}]},
{title:"9. Time conversions in simple interest",body:["The time unit must agree with the rate. If the rate is per annum and time is given in months, convert months to years before substitution.","12 months=1 year, so m months=m/12 years."],examples:[{q:"Find simple interest on ₦80,000 at 9% per annum for 8 months.",steps:["Convert time: 8 months=8/12 year=2/3 year.","I=80,000×9×(2/3)/100.","9×2/3=6.","I=6% of ₦80,000=₦4,800."],answer:"₦4,800"},{q:"Find interest on ₦36,000 at 10% per annum for 18 months.",steps:["18 months=18/12=1.5 years.","I=36,000×10×1.5/100.","10×1.5=15%, so I=15% of 36,000."],answer:"₦5,400"}]},
{title:"10. Reverse simple-interest problems",body:["The same formula can be rearranged when principal, rate or time is unknown. Keep the meaning visible rather than memorising several disconnected formulas.","From I=PRT/100: P=100I/(RT), R=100I/(PT), and T=100I/(PR)."],examples:[{q:"₦60,000 earns ₦9,000 simple interest in 3 years. Find the annual rate.",steps:["I=PRT/100.","9,000=60,000×R×3/100.","60,000×3/100=1,800, so 9,000=1,800R.","R=9,000÷1,800=5."],answer:"5% per annum"},{q:"At 6% simple interest, how long will ₦40,000 take to earn ₦7,200?",steps:["7,200=40,000×6×T/100.","40,000×6/100=2,400.","7,200=2,400T.","T=3 years."],answer:"3 years"}]},
{title:"11. Commission",body:["Commission is payment calculated from sales or transactions, usually as a percentage. Identify the amount on which commission is based.","If a worker also receives a fixed salary, commission and salary are separate amounts that must be added when total earnings are requested."],examples:[{q:"A salesperson earns 5% commission on ₦280,000 sales. Find commission.",steps:["Commission=5/100×₦280,000.","=0.05×₦280,000=₦14,000."],answer:"₦14,000"},{q:"A salesperson receives ₦45,000 salary plus 4% commission on ₦600,000 sales. Find total earnings.",steps:["Commission=4% of ₦600,000=₦24,000.","Total earnings=salary+commission=₦45,000+₦24,000."],answer:"₦69,000"},{q:"A salesperson earned ₦18,000 commission at 6%. Find the sales value.",steps:["0.06×sales=₦18,000.","sales=18,000÷0.06=₦300,000."],answer:"₦300,000"}]},
{title:"12. Multi-step commercial reasoning",body:["Real commercial questions often combine two or more ideas. Work in the order events occur and keep each base quantity clear.","A discount changes what the buyer pays; profit compares selling price with cost price. Those percentages may use different bases."],examples:[{q:"A trader buys an item for ₦48,000, marks it at ₦75,000 and gives a 20% discount. Find the actual selling price and profit percentage.",steps:["Discount=20% of ₦75,000=₦15,000.","Actual SP=₦75,000−₦15,000=₦60,000.","Profit=₦60,000−₦48,000=₦12,000.","Profit%=12,000/48,000×100%=25%."],answer:"SP ₦60,000; profit 25%"},{q:"A trader wants 20% profit after giving a 10% discount. If CP=₦45,000, what marked price is needed?",steps:["Required SP for 20% profit=120% of ₦45,000=₦54,000.","A 10% discount means actual SP is 90% of marked price.","0.90×MP=₦54,000.","MP=₦54,000÷0.90=₦60,000.","Check: 10% discount on 60,000 is 6,000, leaving 54,000."],answer:"Marked price = ₦60,000"}]},
{title:"13. Mastery and reasonableness checks",body:["Before accepting an answer, ask whether its direction makes sense: a discounted price should be below marked price; a selling price at a profit should be above cost price; a loss selling price should be below cost price; interest should reflect principal, rate and time.","A learner is ready when the unknown can move position—profit, CP, SP, rate, time, discount, marked price or commission—and the learner can reconstruct the relationship instead of depending on one memorised question form."]}],mistakes:["Do not calculate profit or loss before identifying CP and SP.","Profit/loss percentage normally uses cost price as its base.","Discount percentage uses marked price as its base.","Discount is the reduction, not the final amount paid.","A reverse percentage problem cannot usually be solved by simply subtracting the percentage from the final value.","For simple interest, make the time unit agree with the rate.","Amount in simple interest means principal plus interest.","Commission may need to be added to fixed salary when total earnings are requested.","In multi-step questions, identify which percentage applies to which base before calculating."]},
"Approximation":{title:"Approximation",objectives:["Approximate to required decimal places","Approximate to required significant figures","Choose and justify the correct degree of accuracy","Solve quantitative aptitude problems"],sections:[
{title:"1. What approximation means",body:["Approximation replaces a number with a nearby value that is easier or suitable for the required accuracy. The answer is not exact, so the requested degree of accuracy matters."]},
{title:"2. Decimal places",body:["Decimal places count digits after the decimal point. Keep the required digit, inspect the next digit: 0–4 keep; 5–9 increase the kept digit by 1."],example:{q:"Round 18.3764 to 2 decimal places.",steps:["Two decimal places keeps 18.37 initially","The next digit is 6","6 ≥ 5, so increase the hundredths digit 7 to 8"],answer:"18.38"}},
{title:"3. Significant figures",body:["Significant figures begin at the first non-zero digit. Leading zeros only locate the decimal point and are not significant."],example:{q:"Round 0.006482 to 2 significant figures.",steps:["First significant digit is 6; second is 4","Next digit is 8, so round 4 upward to 5"],answer:"0.0065"}},
{title:"4. Large numbers and carrying",body:["Rounding can change several places when a kept digit becomes 10."],example:{q:"Round 99,650 to 3 significant figures.",steps:["First three significant digits are 9, 9, 6","Next digit is 5, so 996 rounds to 997 at the required place","Replace following places with zeros"],answer:"99,700"}},
{title:"5. Reasonableness",body:["Approximation is useful for checking calculations. Estimate first, then compare the exact result with the estimate."]}],mistakes:["Decimal places and significant figures are not the same.","Leading zeros are not significant.","Do not drop place-value zeros in large rounded numbers."]},
"Multiplication and Division of Directed Numbers":{title:"Multiplication and Division of Directed Numbers",objectives:["Use square/square-root tables","Interpret tables, charts, records and schedules","Multiply and divide positive and negative numbers correctly"],sections:[
{title:"1. Directed numbers",body:["A directed number carries a sign showing direction relative to zero: positive can represent gain, rise or movement one way; negative can represent loss, fall or the opposite direction.","The sign is part of the number."]},
{title:"2. Sign rules for multiplication",body:["Same signs give a positive product. Different signs give a negative product.","Understand the pattern: 3×2=6, 2×2=4, 1×2=2, 0×2=0, (−1)×2=−2. Continuing the pattern explains why negative × positive is negative."],example:{q:"Calculate (−7) × 6 and (−7) × (−6).",steps:["Different signs: (−7)×6 is negative; 7×6=42 → −42","Same signs: (−7)×(−6) is positive; 7×6=42"],answer:"−42 and +42"}},
{title:"3. Sign rules for division",body:["Division reverses multiplication, so the same sign pattern applies: same signs positive; different signs negative."],example:{q:"Evaluate −84 ÷ 12 and −84 ÷ −12.",steps:["84÷12=7","Different signs → −7","Same signs → +7"],answer:"−7 and 7"}},
{title:"4. Tables, charts and schedules",body:["Read headings, units and direction before calculating. A table is evidence; do not invent values not shown."],example:{q:"A temperature changes from −4°C to 8°C. What is the rise?",steps:["Rise = final − initial","= 8 − (−4)","= 8 + 4"],answer:"12°C"}},
{title:"5. Squares and roots from tables",body:["When using a printed/digital square-root table, identify the number, locate the corresponding entry and check the result by squaring approximately. A table is a tool, not a replacement for understanding square and root."]}],mistakes:["Do not apply addition sign rules to multiplication.","A negative sign is not decoration.","Read chart units before using values."]},
"Algebraic Expressions":{title:"Algebraic Expressions",objectives:["Expand expressions","Factorise simple expressions","Use an area/quadratic box to connect expansion and factorisation","Simplify algebraic fractions with monomial denominators","Model and solve word problems"],sections:[
{title:"1. Language of algebra",body:["A term is a number, variable or product separated by + or −. A coefficient multiplies a variable. Like terms have the same variable part and powers.","Expansion removes brackets by multiplication; factorisation reverses expansion by finding common factors."]},
{title:"2. Expand a(b+c)",body:["The outside factor multiplies every term inside the bracket."],example:{q:"Expand 4(3x − 5).",steps:["4×3x = 12x","4×(−5)=−20"],answer:"12x − 20"}},
{title:"3. Expand two binomials",body:["Every term in the first bracket must multiply every term in the second. An area/quadratic box helps make all four products visible."],example:{q:"Expand (x+3)(x+5).",steps:["x×x=x²","x×5=5x","3×x=3x","3×5=15","Combine like terms: 5x+3x=8x"],answer:"x² + 8x + 15"}},
{title:"4. Factorisation",body:["Factorisation asks which factor is common to every term. Divide each term by that common factor to build the bracket."],example:{q:"Factorise 12x² + 18x.",steps:["HCF of 12 and 18 is 6","Both terms contain x","Common factor = 6x","12x²÷6x=2x; 18x÷6x=3"],answer:"6x(2x+3)"}},
{title:"5. Algebraic fractions",body:["Factor numerator and denominator where possible, then cancel factors—not terms joined by addition."],example:{q:"Simplify 12x²y / 18xy².",steps:["12/18 = 2/3","x²/x = x","y/y² = 1/y"],answer:"2x/(3y)"}},
{title:"6. Word modelling",body:["Define the unknown first, translate the words carefully, then simplify."],example:{q:"A rectangle has length (x+4) cm and width x cm. Write its area.",steps:["Area = length × width","= (x+4)x","= x²+4x"],answer:"x² + 4x cm²"}}
],mistakes:["Do not multiply only the first term inside a bracket.","Cancel factors, not added terms.","Combine only like terms."]},
"Simple Equations":{title:"Simple Equations",objectives:["Understand equality as balance","Solve one-variable equations","Check solutions by substitution","Model real-life situations with equations"],sections:[
{title:"1. Equation as a balance",body:["An equation states that two expressions have equal value. Whatever valid operation you perform on one side must be performed on the other to preserve equality."]},
{title:"2. One-step and two-step equations",body:["Undo operations in reverse order while preserving the balance."],example:{q:"Solve 3x − 4 = 17.",steps:["Add 4 to both sides: 3x = 21","Divide both sides by 3: x = 7","Check: 3(7)−4=21−4=17"],answer:"x = 7"}},
{title:"3. Variables on both sides",body:["Collect variable terms on one side and constants on the other using equal operations."],example:{q:"Solve 5x + 2 = 3x + 18.",steps:["Subtract 3x from both sides: 2x+2=18","Subtract 2: 2x=16","Divide by 2: x=8","Check: 42=42"],answer:"x = 8"}},
{title:"4. Equations from words",body:["Choose a variable, translate the relationship, solve, then answer in the original context."],example:{q:"A number is doubled and 5 is added. The result is 23. Find the number.",steps:["Let the number be x","2x+5=23","2x=18","x=9"],answer:"The number is 9."}}
],mistakes:["Do not 'move' terms without understanding the inverse operation.","Always check by substitution.","Define the unknown in word problems."]},
"Linear Inequalities":{title:"Linear Inequalities",objectives:["Identify inequalities in one variable","Solve inequalities","Represent solutions on number lines","Solve inequality word problems"],sections:[
{title:"1. Inequality language",body:["< means less than, > greater than, ≤ less than or equal to, ≥ greater than or equal to. Unlike an equation, an inequality often has many solutions."]},
{title:"2. Solve like an equation—until a negative multiplication/division",body:["Adding or subtracting the same number preserves order. Multiplying or dividing both sides by a negative reverses the inequality sign."],example:{q:"Solve 3x + 2 < 14.",steps:["Subtract 2: 3x < 12","Divide by positive 3: x < 4"],answer:"x < 4"}},
{title:"3. Why the sign reverses",body:["Because −2 < 1, multiplying both by −1 gives 2 > −1. Negative multiplication reflects numbers across zero, reversing order."],example:{q:"Solve −2x ≥ 10.",steps:["Divide both sides by −2","Because the divisor is negative, reverse ≥ to ≤","x ≤ −5","Check x=−6: −2(−6)=12 ≥10"],answer:"x ≤ −5"}},
{title:"4. Number-line representation",body:["Use an open circle for < or > because the boundary is excluded. Use a filled circle for ≤ or ≥ because the boundary is included. Shade/arrow toward all allowed values."]},
{title:"5. Word problem",body:["Translate limit words carefully: 'at most' means ≤; 'at least' means ≥; 'more than' means >; 'less than' means <."],example:{q:"A bus can carry at most 54 people. There are already 38 aboard. If x more enter, form and solve an inequality.",steps:["38+x ≤54","Subtract 38: x≤16"],answer:"At most 16 more people can enter."}}
],mistakes:["Reverse the sign only when multiplying/dividing by a negative.","Open and filled circles have different meanings.","An inequality answer is usually a set/range, not one number."]},
"Graph":{title:"Graphs and the Cartesian Plane",objectives:["Identify x- and y-axes","Plot ordered pairs","Prepare tables of values","Plot and interpret linear equations","Interpret real-life linear graphs"],sections:[
{title:"1. Cartesian plane",body:["The horizontal axis is x; the vertical axis is y. They meet at the origin (0,0). An ordered pair is written (x,y): move along x first, then y."]},
{title:"2. Quadrants and plotting",body:["Signs locate points: (+,+), (−,+), (−,−), (+,−) in quadrants I–IV respectively."],example:{q:"Describe how to plot (−3,2).",steps:["Start at (0,0)","Move 3 units left because x=−3","Move 2 units up because y=2"],answer:"Plot the point at (−3,2), in quadrant II."}},
{title:"3. Table of values",body:["A linear equation links x and y. Choose x-values and calculate corresponding y-values before plotting."],example:{q:"Prepare values for y=2x+1 when x=−1,0,1,2.",steps:["x=−1: y=−2+1=−1","x=0: y=1","x=1: y=3","x=2: y=5"],answer:"Points: (−1,−1),(0,1),(1,3),(2,5)."}},
{title:"4. Plot and interpret a straight line",body:["Choose a consistent scale, label axes and units, plot accurately, then draw the straight line through the points. A point on the line satisfies the equation."]},
{title:"5. Real-life graphs",body:["In a distance-time graph, slope shows rate of change: steeper segments represent greater speed when scales are the same; horizontal distance means no change in distance."],example:{q:"A cyclist travels 30 km in 2 h at constant speed. Find the gradient/rate.",steps:["Rate = change in distance/change in time","=30/2"],answer:"15 km/h"}}
],mistakes:["Coordinates are x first, y second.","Never omit graph scale and units.","Do not join unrelated data blindly; interpret what the line means."]},
"Plane Figure/ Shapes":{title:"Plane Figures, Shapes and Scale Drawing",objectives:["State properties of parallelogram, rhombus and kite","Recognise shapes","Draw to scale","Convert actual and scaled lengths","Solve measurement problems"],sections:[
{title:"1. Properties matter more than appearance",body:["A parallelogram has both pairs of opposite sides parallel and equal; opposite angles are equal and diagonals bisect each other.","A rhombus is a parallelogram with all four sides equal; its diagonals bisect at right angles.","A kite has two pairs of adjacent equal sides; one diagonal is a line of symmetry in the usual kite and the diagonals meet at right angles."]},
{title:"2. Scale drawing",body:["A scale compares drawing length with actual length in the same units. For 1:100, 1 cm on the drawing represents 100 cm in reality."]},
{title:"3. Actual to drawing",body:["Convert units first, then apply the scale."],example:{q:"At scale 1:200, how long should a 10 m wall be on the drawing?",steps:["10 m = 1000 cm","Drawing length = 1000÷200 cm"],answer:"5 cm"}},
{title:"4. Drawing to actual",body:["Multiply drawing length by the scale denominator, then convert to a sensible unit."],example:{q:"On a 1:500 plan, two points are 7.2 cm apart. Find actual distance.",steps:["Actual = 7.2×500 cm = 3600 cm","3600 cm ÷100 =36 m"],answer:"36 m"}},
{title:"5. Measurement problem",body:["A good scale drawing states the scale, uses accurate ruler/protractor work and labels dimensions. Never measure from a diagram declared 'not to scale'."]}],mistakes:["Convert units before applying scale.","A rhombus need not be a square.","Do not classify shapes only by how they look."]},
"Angles":{title:"Angles, Polygons, Elevation and Depression",objectives:["Find angle sums in triangles and quadrilaterals","Find interior-angle sums of polygons","Distinguish elevation and depression","Use scale drawing for distance/height problems","Relate elevation and depression"],sections:[
{title:"1. Triangle and quadrilateral foundations",body:["Angles in any triangle sum to 180°. A quadrilateral can be split into two triangles, so its interior angles sum to 360°."]},
{title:"2. Polygon interior-angle sum",body:["From one vertex, an n-sided convex polygon can be divided into n−2 triangles. Therefore sum of interior angles = (n−2)×180°."],example:{q:"Find the sum of interior angles of a hexagon.",steps:["n=6","(n−2)×180°=(6−2)×180°","=4×180°"],answer:"720°"}},
{title:"3. Missing angle",body:["Use the correct total, then subtract known angles."],example:{q:"Three angles of a quadrilateral are 85°, 110° and 72°. Find the fourth.",steps:["Quadrilateral sum=360°","Known sum=85+110+72=267°","Missing=360−267"],answer:"93°"}},
{title:"4. Elevation and depression",body:["Angle of elevation is measured upward from a horizontal line of sight. Angle of depression is measured downward from a horizontal line of sight.","With parallel horizontal lines, corresponding/alternate angle relationships explain why an angle of depression can equal the corresponding angle of elevation."]},
{title:"5. Scale-drawing application",body:["At JSS2, construct the given angle and scaled distance accurately, complete the right-triangle representation, then measure the requested scaled length and convert back. Do not introduce trigonometric ratios when the curriculum asks for scale drawing."]}],mistakes:["Use (n−2)×180°, not n×180°.","Elevation/depression are measured from horizontal, not vertical.","Respect the stated scale."]},
"Bearing":{title:"Bearing",objectives:["Identify major and minor cardinal points","Locate objects using compass and three-digit bearings","Measure distances using scale drawing"],sections:[
{title:"1. Direction foundation",body:["Major cardinal points are North, East, South and West. Minor/intercardinal points include NE, SE, SW and NW."]},
{title:"2. Three-digit bearings",body:["A three-digit bearing is measured clockwise from North and written with three digits: 045°, 090°, 180°, 270°. Always begin at the north line of the starting point."]},
{title:"3. Compass bearings",body:["Compass notation describes direction from North or South toward East or West, such as N30°E. Keep it distinct from three-digit bearing notation."]},
{title:"4. Locate an object",body:["Draw North at the starting point, place the protractor centre at the point, measure clockwise, draw the bearing ray, then mark the scaled distance."],example:{q:"A clinic is 6 km from a school on bearing 060°. Use scale 1 cm : 2 km. How far is it on the drawing?",steps:["Drawing distance=6÷2 cm=3 cm","Draw North at school","Measure 060° clockwise from North","Draw a 3 cm ray"],answer:"The clinic is marked 3 cm from the school along bearing 060°."}},
{title:"5. Reverse bearing",body:["For two points, the reverse direction differs by 180°. Add 180° if the bearing is below 180°; subtract 180° if it is 180° or more."],example:{q:"If B is on bearing 070° from A, find the bearing of A from B.",steps:["070°<180°, so add 180°","70°+180°=250°"],answer:"250°"}}
],mistakes:["Bearings are measured clockwise from North.","Write three-digit bearings with leading zeros.","A distance needs a scale; a bearing alone gives direction, not distance."]},
"Construction":{title:"Geometrical Construction",objectives:["Construct triangles from sufficient measurements","Construct SSS, SAS and ASA/AAS cases","Bisect an angle accurately","Explain construction arcs"],sections:[
{title:"1. Construction is exact geometry",body:["Use ruler for straight lines, compasses for equal distances/arcs and protractor only where the specified construction permits angle measurement. Keep construction arcs visible because they show why the result is valid."]},
{title:"2. SSS triangle",body:["When all three sides are known, draw one side as base. From each endpoint draw arcs with radii equal to the other two sides. Their intersection fixes the third vertex."],example:{q:"Construct triangle ABC with AB=6 cm, AC=5 cm, BC=4 cm.",steps:["Draw AB=6 cm","Centre A, radius 5 cm: draw an arc","Centre B, radius 4 cm: draw an intersecting arc","Call intersection C","Join AC and BC","Measure sides to check"],answer:"Triangle ABC is fixed by the three side lengths."}},
{title:"3. SAS triangle",body:["Two sides and the included angle determine a triangle: draw one side, construct the included angle at the correct endpoint, mark the second side length, then join the remaining vertices."]},
{title:"4. ASA/AAS triangle",body:["Draw the known side, construct the given angle rays at the required endpoints; their intersection determines the third vertex."]},
{title:"5. Bisect an angle",body:["An angle bisector divides an angle into two equal angles."],example:{q:"Bisect ∠A using ruler and compasses.",steps:["Centre A, draw an arc cutting both arms at P and Q","With equal compass radius, draw arcs from P and Q to intersect at R","Join A to R","AR is the angle bisector because R is equally distant from P and Q"],answer:"∠PAR = ∠RAQ."}}
],mistakes:["Do not erase construction arcs.","Use the included angle in SAS correctly.","A sketch is not a construction."]},
"Data Presentation":{title:"Data Presentation",objectives:["Order data","Construct frequency tables","Read pie charts","Calculate and interpret interquartile range","Construct and compare box plots"],sections:[
{title:"1. Raw data to ordered data",body:["Raw data are observations as collected. Ordering them from least to greatest reveals position and makes quartiles easier to determine."]},
{title:"2. Frequency tables",body:["Frequency tells how many times a value/category occurs. Tally carefully and verify that total frequency equals the number of observations."],example:{q:"For 2,3,2,5,3,2,4 construct frequencies.",steps:["2 occurs 3 times","3 occurs 2 times","4 occurs 1 time","5 occurs 1 time","Total=3+2+1+1=7, matching 7 observations"],answer:"Frequencies: 2→3, 3→2, 4→1, 5→1."}},
{title:"3. Reading pie charts",body:["A full circle is 360°. Sector fraction = sector angle/360 = category frequency/total. Use this relationship in either direction."],example:{q:"A 90° sector represents books in a survey of 80 learners. How many chose books?",steps:["90/360=1/4","1/4×80=20"],answer:"20 learners"}},
{title:"4. Quartiles and IQR",body:["Q1 marks the lower quarter, Q2 is the median, Q3 marks the upper quarter. IQR=Q3−Q1 and measures the spread of the middle 50% of the data.","Use one consistent school convention for locating quartiles and state it when an even-sized data set could be treated differently."],example:{q:"For 2,4,5,7,8,10,12,14 find IQR using median-of-halves.",steps:["Lower half: 2,4,5,7 → Q1=(4+5)/2=4.5","Upper half: 8,10,12,14 → Q3=(10+12)/2=11","IQR=11−4.5"],answer:"IQR = 6.5"}},
{title:"5. Box plots",body:["A box plot uses five-number summary: minimum, Q1, median, Q3, maximum. The box spans Q1 to Q3; the line inside is the median; whiskers extend to minimum and maximum.","Compare medians for centre and IQRs for middle spread. A larger IQR means the middle half is more spread out."]}],mistakes:["Order data before finding quartiles.","IQR is Q3−Q1, not maximum−minimum.","Pie-chart angles must relate to 360°."]},
"Probability":{title:"Probability",objectives:["Discuss chance events","Determine probabilities of simple events","Use experiments with coins/dice","Apply probability to uncertain everyday events"],sections:[
{title:"1. Chance and uncertainty",body:["Probability measures how likely an event is. Probability 0 means impossible; 1 means certain; values between 0 and 1 describe degrees of likelihood."]},
{title:"2. Outcomes and events",body:["The sample space lists all possible outcomes. An event is one or more outcomes of interest. For equally likely outcomes, P(event)=favourable outcomes/total possible outcomes."],example:{q:"A fair die is rolled. Find P(rolling an even number).",steps:["Sample space={1,2,3,4,5,6}: 6 equally likely outcomes","Even outcomes={2,4,6}: 3 favourable outcomes","P(even)=3/6"],answer:"1/2"}},
{title:"3. Coin experiment",body:["Theoretical probability predicts from equally likely outcomes; experimental probability uses observed frequency. With more trials, experimental results often become more stable, but need not equal theory exactly."],example:{q:"A coin gives 27 heads in 50 tosses. Find experimental P(head).",steps:["Experimental probability=observed heads/total tosses","=27/50"],answer:"0.54 or 54%"}},
{title:"4. Complement",body:["An event and 'not the event' together cover all possibilities, so P(not A)=1−P(A)."],example:{q:"If P(rain)=0.3, find P(no rain).",steps:["P(no rain)=1−0.3"],answer:"0.7"}},
{title:"5. Everyday interpretation",body:["Probability supports decisions under uncertainty but does not guarantee a single outcome. A 70% chance does not mean the event must happen.","Use trustworthy data and define the population/time period before drawing real-life conclusions."]}],mistakes:["Probability must lie from 0 to 1 inclusive.","Do not confuse experimental frequency with certainty.","List the sample space before counting favourable outcomes."]}
};
export default function JSS2PremiumMathLesson({topic,onExercise}:{topic:string;onExercise:()=>void}){const l=lessons[topic];if(!l)return null;return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS2 MATHEMATICS · NERDC SEPTEMBER 2025</span><h1>{l.title}</h1><p>Concept-first teaching, fully worked reasoning and curriculum-level application.</p></header><section className="wn-objectives"><h2>Learning Objectives</h2><ul>{l.objectives.map(x=><li key={x}>{x}</li>)}</ul></section>{l.sections.map(s=><section className="wn-section" key={s.title}><h3>{s.title}</h3>{s.body.map((p,i)=><p key={i}>{p}</p>)}{[...(s.example?[s.example]:[]),...(s.examples||[])].map((ex,ei)=><div className="fraction-working" key={ei}><div className="example-question"><span>{ei===0?'WORKED EXAMPLE':`COMPLEMENTARY EXAMPLE ${ei+1}`}</span><strong>{ex.q}</strong></div><div className="math-stack">{ex.steps.map((x,i)=><div className="math-line" key={i}>{x}</div>)}<div className="math-line math-result">{ex.answer}</div></div></div>)}</section>)}<section className="wn-section"><h3>Common Mistakes and Misconceptions</h3><div className="lesson-rule">{l.mistakes.map(x=><span key={x}>{x}</span>)}</div></section><section className="wn-section"><h3>Mastery Standard</h3><p>Do not move on because a rule has been memorised. You should be able to explain the idea, complete the method accurately, solve an unfamiliar application and check whether the answer is reasonable.</p></section><div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}
export const jss2PremiumMathTopics=Object.keys(lessons);