'use client';
import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>;
const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
const Rule=({children}:{children:React.ReactNode})=><div className="lesson-rule">{children}</div>;
export default function JSS2WholeNumbersLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS2 MATHEMATICS · NUMBER AND NUMERATION</span><h1>Whole Numbers</h1><p>Standard form, prime factors, prime factorisation, LCM and HCF — built from meaning before method.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul><li>Express whole and decimal numbers in standard form and convert them back.</li><li>Identify prime numbers and prime factors, including primes below 200.</li><li>Express numbers as products of prime factors and in index form.</li><li>Find LCM and HCF from prime factorisation and explain why the methods work.</li></ul></section>
<section className="wn-section"><h3>1. Standard Form</h3><p>Standard form writes a number as <b>a × 10ⁿ</b>, where <b>1 ≤ a &lt; 10</b>. The power of 10 records how far the decimal point has moved.</p><Rule><span>Large ordinary number → positive power of 10.</span><span>Small decimal between 0 and 1 → negative power of 10.</span><span>The first number must be at least 1 but less than 10.</span></Rule></section>
<section className="wn-section"><h3>2. Whole Numbers to Standard Form</h3><W q="Write 450,000 in standard form."><L>Place the decimal after the first non-zero digit: 4.5.</L><L>To recover 450,000 from 4.5, move the decimal 5 places right.</L><L strong>450,000 = 4.5 × 10⁵.</L><L>Check: 4.5 × 100,000 = 450,000.</L></W><W q="Write 72,300,000 in standard form."><L>72,300,000 → 7.23.</L><L>The decimal moved 7 places.</L><L strong>72,300,000 = 7.23 × 10⁷.</L></W></section>
<section className="wn-section"><h3>3. Decimal Numbers to Standard Form</h3><W q="Write 0.00056 in standard form."><L>The first non-zero digit is 5, so write 5.6.</L><L>To recover 0.00056, move the decimal 4 places left, so the exponent is negative.</L><L strong>0.00056 = 5.6 × 10⁻⁴.</L></W><W q="Write 0.0325 in standard form."><L>0.0325 → 3.25.</L><L>The decimal must move 2 places left to recover the original number.</L><L strong>0.0325 = 3.25 × 10⁻².</L></W></section>
<section className="wn-section"><h3>4. Standard Form Back to Ordinary Numbers</h3><W q="Write 6.04 × 10⁵ as an ordinary number."><L>10⁵ means move the decimal 5 places right.</L><L strong>6.04 × 10⁵ = 604,000.</L></W><W q="Write 8.2 × 10⁻⁴ as a decimal."><L>10⁻⁴ means move the decimal 4 places left.</L><L strong>8.2 × 10⁻⁴ = 0.00082.</L></W><W q="Write 0.00000704 in standard form."><L>The first non-zero digit is 7, so write 7.04.</L><L>To return to the original number, move 6 places left.</L><L strong>0.00000704 = 7.04 × 10⁻⁶.</L></W><W q="Write 3.006 × 10⁻³ as an ordinary decimal."><L>Move the decimal 3 places left.</L><L strong>3.006 × 10⁻³ = 0.003006.</L></W></section>
<section className="wn-section"><h3>5. Prime Numbers — Establish the Foundation</h3><p>A <b>prime number</b> is a whole number greater than 1 with exactly two positive factors: 1 and itself. Examples include 2, 3, 5, 7, 11, 13, 17 and 19. The number 1 is not prime. A number greater than 1 with more than two factors is composite.</p><W q="Is 37 prime?"><L>Test prime divisors up to √37, which is a little above 6.</L><L>2 does not divide 37 because 37 is odd.</L><L>3 does not divide 37 because 3+7=10.</L><L>5 does not divide 37 because it does not end in 0 or 5.</L><L strong>37 is prime.</L></W><W q="Is 91 prime?"><L>√91 is a little above 9, so test prime divisors 2, 3, 5 and 7.</L><L>91 is odd; digit sum is 10; it does not end in 0 or 5.</L><L>91 ÷ 7 = 13 exactly.</L><L strong>91 is composite: 91 = 7 × 13.</L></W><W q="Identify the primes among 1, 2, 29, 51 and 97."><L>1 is not prime.</L><L>2 is prime and is the only even prime.</L><L>29 has no divisor other than 1 and 29.</L><L>51 = 3 × 17, so it is composite.</L><L>97 is not divisible by 2, 3, 5 or 7; these cover primes up to √97.</L><L strong>The primes are 2, 29 and 97.</L></W><Rule><span>2 is the only even prime.</span><span>1 is neither prime nor composite.</span><span>Test possible prime divisors systematically rather than guessing.</span></Rule></section>
<section className="wn-section"><h3>6. Prime Factors and Prime Factorisation</h3><p>A factor divides a number exactly. A <b>prime factor</b> is a factor that is prime. Prime factorisation breaks a number completely into prime building blocks.</p><W q="Express 180 as a product of prime factors."><L>180 ÷ 2 = 90.</L><L>90 ÷ 2 = 45.</L><L>45 ÷ 3 = 15.</L><L>15 ÷ 3 = 5.</L><L>5 ÷ 5 = 1.</L><L>180 = 2 × 2 × 3 × 3 × 5.</L><L strong>180 = 2² × 3² × 5.</L><L>Check: 4 × 9 × 5 = 180.</L></W><W q="Express 252 as a product of prime factors."><L>252÷2=126; 126÷2=63.</L><L>63÷3=21; 21÷3=7; 7÷7=1.</L><L>252=2×2×3×3×7.</L><L strong>252=2²×3²×7.</L></W><W q="Express 1,000 as a product of prime factors."><L>1,000=10×10×10.</L><L>Each 10=2×5.</L><L>So 1,000=(2×5)³.</L><L strong>1,000=2³×5³.</L></W></section>
<section className="wn-section"><h3>7. Why Prime Factors Matter</h3><p>Prime factors reveal the exact multiplicative structure of a number. HCF asks which prime building blocks the numbers share. LCM asks which building blocks are required to contain every number. This is why prime factorisation is useful instead of being a rule to memorise.</p></section>
<section className="wn-section"><h3>8. LCM from Prime Factors</h3><p>The LCM is the smallest positive number divisible by every given number. Use every prime that appears and take the <b>highest power required</b>.</p><W q="Find the LCM of 24, 36 and 40."><L>24 = 2³ × 3.</L><L>36 = 2² × 3².</L><L>40 = 2³ × 5.</L><L>Highest required powers: 2³, 3² and 5.</L><L>LCM = 2³ × 3² × 5 = 8 × 9 × 5.</L><L strong>LCM = 360.</L><L>Check: 360÷24=15, 360÷36=10, 360÷40=9.</L></W><W q="Find the LCM of 18 and 45."><L>18=2×3².</L><L>45=3²×5.</L><L>Use every required prime at its highest power: 2×3²×5.</L><L strong>LCM=90.</L><L>Check: 90÷18=5 and 90÷45=2.</L></W><W q="Find the least number divisible by 8, 12 and 15."><L>This wording asks for LCM.</L><L>8=2³; 12=2²×3; 15=3×5.</L><L>LCM=2³×3×5.</L><L strong>LCM=120.</L></W></section>
<section className="wn-section"><h3>9. HCF from Prime Factors</h3><p>The HCF is the greatest number that divides every given number exactly. Keep only primes present in <b>all</b> the numbers and take their <b>lowest shared powers</b>.</p><W q="Find the HCF of 72, 108 and 180."><L>72 = 2³ × 3².</L><L>108 = 2² × 3³.</L><L>180 = 2² × 3² × 5.</L><L>Only 2 and 3 occur in all three.</L><L>Lowest shared powers: 2² and 3².</L><L>HCF = 2² × 3² = 4 × 9.</L><L strong>HCF = 36.</L><L>Check: 72÷36=2, 108÷36=3, 180÷36=5.</L></W><W q="Find the HCF of 84 and 126."><L>84=2²×3×7.</L><L>126=2×3²×7.</L><L>Shared primes at lowest powers: 2×3×7.</L><L strong>HCF=42.</L></W><W q="Find the greatest number that divides 96, 144 and 168 exactly."><L>The wording asks for HCF.</L><L>96=2⁵×3; 144=2⁴×3²; 168=2³×3×7.</L><L>Shared lowest powers are 2³×3.</L><L strong>HCF=24.</L></W></section>
<section className="wn-section"><h3>10. HCF and LCM — Do Not Swap the Rules</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th></th><th>HCF</th><th>LCM</th></tr></thead><tbody><tr><td>Idea</td><td>what every number shares</td><td>what is needed to contain every number</td></tr><tr><td>Primes</td><td>shared primes only</td><td>every required prime</td></tr><tr><td>Powers</td><td>lowest shared powers</td><td>highest required powers</td></tr></tbody></table></div></section>
<section className="wn-section"><h3>11. Quantitative Reasoning</h3><W q="Three lights flash every 12 s, 18 s and 30 s. When will they next flash together?"><L>This is a repeating-cycle question, so use LCM.</L><L>12=2²×3; 18=2×3²; 30=2×3×5.</L><L>LCM=2²×3²×5=180.</L><L strong>They next flash together after 180 seconds = 3 minutes.</L></W><W q="84 red beads and 126 blue beads are put into the greatest possible number of identical groups. How many groups?"><L>This asks for greatest equal grouping, so use HCF.</L><L>84=2²×3×7; 126=2×3²×7.</L><L>HCF=2×3×7=42.</L><L strong>42 groups.</L><L>Each group has 2 red and 3 blue beads.</L></W></section>
<section className="wn-section"><h3>12. Common Mistakes</h3><Rule><span>Standard form begins with a number from 1 up to but not including 10.</span><span>Do not call 1 prime.</span><span>Prime factorisation must finish with prime factors only.</span><span>HCF uses lowest shared powers; LCM uses highest required powers.</span></Rule></section>
<section className="wn-section"><h3>13. Mastery Check</h3><p>You are ready when you can convert both ways between ordinary numbers and standard form, identify and obtain prime factors, write prime factorisations in index form, find LCM/HCF, and explain why the power rule changes between HCF and LCM.</p></section>
<div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}