'use client'; import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>; const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
export default function LCMLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS1 MATHEMATICS · WHOLE NUMBERS</span><h1>Lowest Common Multiple (LCM)</h1><p>Understand common multiples and find the lowest one by the multiple, factor and index methods.</p></header><section className="wn-objectives"><h2>NERDC-Aligned Objectives</h2><ul><li>Identify common multiples.</li><li>Find LCM of whole numbers.</li><li>Use multiple, factor and index methods.</li><li>Solve problems with two or three whole numbers.</li></ul></section>
<section className="wn-section"><h3>1. Multiples</h3><W q="Find the first common multiple of 4 and 6."><L>4: 4, 8, 12, 16, 20, 24...</L><L>6: 6, 12, 18, 24...</L><L>12 is the first number in both lists.</L><L strong>LCM(4,6) = 12</L></W></section>
<section className="wn-section"><h3>2. Multiple Method</h3><W q="Find LCM of 8 and 12."><L>8: 8, 16, 24, 32...</L><L>12: 12, 24, 36...</L><L strong>LCM = 24</L></W></section>
<section className="wn-section"><h3>3. Factor Method</h3><W q="Find LCM of 12 and 18."><L>12 = 2 × 2 × 3 = 2² × 3</L><L>18 = 2 × 3 × 3 = 2 × 3²</L><L>Use every prime needed at its greatest required repetition.</L><L>LCM = 2² × 3² = 4 × 9</L><L strong>LCM = 36</L></W></section>
<section className="wn-section"><h3>4. Index Method</h3><W q="Find LCM of 24 and 36."><L>24 = 2³ × 3</L><L>36 = 2² × 3²</L><L>Greatest powers: 2³ and 3².</L><L>LCM = 2³ × 3² = 72</L><L strong>LCM = 72</L></W></section>
<section className="wn-section"><h3>5. Three Numbers</h3><W q="Find LCM of 6, 8 and 12."><L>6 = 2 × 3</L><L>8 = 2³</L><L>12 = 2² × 3</L><L>LCM = 2³ × 3</L><L strong>LCM = 24</L><L>24 ÷ 6 = 4, 24 ÷ 8 = 3, 24 ÷ 12 = 2. Check passed.</L></W></section>
<section className="wn-section"><h3>6. Real-Life Cycle</h3><W q="One event repeats every 6 minutes and another every 8 minutes. They occur together now. When will they next occur together?"><L>Find the first positive time divisible by both 6 and 8.</L><L>LCM(6,8) = 24.</L><L strong>They next occur together after 24 minutes.</L></W></section>
<section className="wn-section"><h3>7. LCM or HCF?</h3><div className="lesson-rule"><span><b>LCM:</b> lowest positive common multiple.</span><span><b>HCF:</b> highest factor common to all numbers.</span><span>Next common cycle suggests LCM.</span><span>Largest equal grouping suggests HCF.</span></div></section>
<section className="wn-section"><h3>8. Check</h3><p>An LCM must be divisible by every original number. If one original number does not divide it exactly, it cannot be their LCM.</p></section><div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}