'use client';
const objectives=['explain what a mathematical comparison symbol communicates','recognise and correctly use =, ≠, <, >, ≤ and ≥','distinguish equality from inequality','compare whole numbers using place value','compare fractions and decimals before choosing a symbol','interpret and translate verbal comparison statements','arrange numbers in ascending and descending order','identify and correct common symbol errors','apply comparison symbols to everyday quantities'];
function MathLine({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
export default function UseOfSymbolsLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS</span><h1>Use of Symbols</h1><p>Understand equality and inequality, compare quantities correctly, and translate mathematical relationships between words and symbols.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. Mathematical Symbols Show Relationships</h3><p>A mathematical symbol can tell us how the quantity on the left relates to the quantity on the right. For example, 7 &gt; 4 says “seven is greater than four”, while 5 = 5 says both sides have the same value.</p><div className="lesson-rule"><span>= means is equal to</span><span>≠ means is not equal to</span><span>&lt; means is less than</span><span>&gt; means is greater than</span><span>≤ means is less than or equal to</span><span>≥ means is greater than or equal to</span></div></section>
<section className="wn-section"><h3>2. Equality: =</h3><p>The equal sign means that the expressions on both sides have exactly the same value. It does not merely mean “the answer comes next”.</p><div className="math-working"><MathLine>3 + 4 = 7</MathLine><MathLine>4 + 3 = 5 + 2</MathLine><MathLine>Left: 4 + 3 = 7</MathLine><MathLine>Right: 5 + 2 = 7</MathLine><MathLine strong>Therefore 4 + 3 = 5 + 2.</MathLine></div></section>
<section className="wn-section"><h3>3. Not Equal To: ≠</h3><p>The symbol ≠ says that two quantities do not have the same value.</p><div className="math-working"><MathLine>7 ≠ 5</MathLine><MathLine>4 + 3 = 7</MathLine><MathLine>7 ≠ 10</MathLine><MathLine strong>Therefore 4 + 3 ≠ 10.</MathLine></div></section>
<section className="wn-section"><h3>4. Greater Than and Less Than</h3><p>The symbol &gt; means “is greater than”; the symbol &lt; means “is less than”. Read the completed statement from left to right.</p><div className="lesson-rule"><span>9 &gt; 4 — nine is greater than four.</span><span>3 &lt; 8 — three is less than eight.</span><span>4 &lt; 9 and 9 &gt; 4 describe the same comparison from opposite directions.</span></div></section>
<section className="wn-section"><h3>5. Compare Whole Numbers by Place Value</h3><Work q="Insert <, > or = between 4,572 and 4,527."><MathLine>Thousands: 4 = 4</MathLine><MathLine>Hundreds: 5 = 5</MathLine><MathLine>Tens: 7 &gt; 2</MathLine><MathLine strong>4,572 &gt; 4,527</MathLine></Work><Work q="Compare 38,416 and 38,461."><MathLine>Ten-thousands: 3 = 3</MathLine><MathLine>Thousands: 8 = 8</MathLine><MathLine>Hundreds: 4 = 4</MathLine><MathLine>Tens: 1 &lt; 6</MathLine><MathLine strong>38,416 &lt; 38,461</MathLine></Work><p>For positive whole numbers with different digit counts, the number with more digits is larger: 999 &lt; 1,000.</p></section>
<section className="wn-section"><h3>6. Greater Than or Equal To: ≥</h3><p>If x ≥ 5, x may equal 5 or be greater than 5.</p><div className="lesson-rule"><span>7 ≥ 5 is true.</span><span>5 ≥ 5 is true.</span><span>4 ≥ 5 is false.</span></div></section>
<section className="wn-section"><h3>7. Less Than or Equal To: ≤</h3><p>If x ≤ 10, x may equal 10 or be less than 10.</p><div className="lesson-rule"><span>8 ≤ 10 is true.</span><span>10 ≤ 10 is true.</span><span>12 ≤ 10 is false.</span></div><p>Equality matters: 5 &lt; 5 is false, but 5 ≤ 5 is true. Likewise, 7 &gt; 7 is false, but 7 ≥ 7 is true.</p></section>
<section className="wn-section"><h3>8. Compare Expressions</h3><Work q="Insert the correct symbol: 6 × 4 □ 20 + 4."><MathLine>6 × 4 = 24</MathLine><MathLine>20 + 4 = 24</MathLine><MathLine strong>6 × 4 = 20 + 4</MathLine></Work><Work q="Compare 5 × 7 and 40 − 3."><MathLine>5 × 7 = 35</MathLine><MathLine>40 − 3 = 37</MathLine><MathLine>35 &lt; 37</MathLine><MathLine strong>5 × 7 &lt; 40 − 3</MathLine></Work></section>
<section className="wn-section"><h3>9. Compare Fractions</h3><p>Do not compare fractions by looking at denominators alone. Compare their actual values.</p><Work q="Compare 3/4 and 2/3."><MathLine>LCM of 4 and 3 = 12</MathLine><MathLine>3/4 = (3 × 3)/(4 × 3) = 9/12</MathLine><MathLine>2/3 = (2 × 4)/(3 × 4) = 8/12</MathLine><MathLine>9/12 &gt; 8/12</MathLine><MathLine strong>3/4 &gt; 2/3</MathLine></Work><p>With equal denominators, compare numerators: 3/8 &lt; 5/8. With equal positive numerators, the fraction with the smaller denominator is larger: 1/3 &gt; 1/5.</p></section>
<section className="wn-section"><h3>10. Compare Decimals by Place Value</h3><Work q="Compare 0.7 and 0.65."><MathLine>0.7 = 0.70</MathLine><MathLine>0.70 &gt; 0.65</MathLine><MathLine strong>Therefore 0.7 &gt; 0.65.</MathLine></Work><p>Do not judge decimal size by the number of written digits. For example, 0.8 = 0.80, so 0.8 &gt; 0.75.</p></section>
<section className="wn-section"><h3>11. Translate Words Into Symbols</h3><div className="lesson-rule"><span>“12 is greater than 7” → 12 &gt; 7</span><span>“4 is less than 9” → 4 &lt; 9</span><span>“15 is equal to 10 plus 5” → 15 = 10 + 5</span><span>“8 is not equal to 11” → 8 ≠ 11</span><span>“x is at least 6” → x ≥ 6</span><span>“y is at most 20” → y ≤ 20</span></div><p>“At least” includes the stated value and everything greater. “At most” includes the stated value and everything less.</p></section>
<section className="wn-section"><h3>12. Read Symbols Back Into Words</h3><div className="lesson-rule"><span>14 &gt; 9 → fourteen is greater than nine.</span><span>6 &lt; 11 → six is less than eleven.</span><span>x ≥ 4 → x is at least 4.</span><span>y ≤ 12 → y is at most 12.</span></div></section>
<section className="wn-section"><h3>13. Ascending and Descending Order</h3><p>Ascending order goes from smallest to largest; descending order goes from largest to smallest.</p><div className="math-working"><MathLine>Numbers: 17, 5, 23, 9</MathLine><MathLine>Ascending: 5 &lt; 9 &lt; 17 &lt; 23</MathLine><MathLine strong>Descending: 23 &gt; 17 &gt; 9 &gt; 5</MathLine></div></section>
<section className="wn-section"><h3>14. Everyday Quantities</h3><p>If one learner has ₦2,500 and another has ₦1,800, then ₦2,500 &gt; ₦1,800. If a container can hold at most 20 litres and L is its content, then L ≤ 20. If a stated requirement is at least 50 marks and s is the score, then s ≥ 50.</p></section>
<section className="wn-section"><h3>15. True or False Statements</h3><Work q="Is 18 − 5 > 10 true?"><MathLine>18 − 5 = 13</MathLine><MathLine>13 &gt; 10</MathLine><MathLine strong>Yes. The statement is true.</MathLine></Work><Work q="Is 4 × 3 ≤ 10 true?"><MathLine>4 × 3 = 12</MathLine><MathLine>12 ≤ 10 is false.</MathLine><MathLine strong>Therefore 4 × 3 ≤ 10 is false.</MathLine></Work></section>
<section className="wn-section"><h3>Common Misconceptions</h3><div className="lesson-rule"><span><b>Do not reverse &lt; and &gt;.</b> Read the completed statement from left to right.</span><span><b>= means equal value.</b> It does not merely announce an answer.</span><span><b>&lt; and ≤ are different.</b> The second includes equality.</span><span><b>Do not compare fractions by denominator alone.</b> Compare the fraction values.</span><span><b>Do not compare decimals as whole-number strings.</b> Compare corresponding decimal places.</span><span><b>At least includes equality.</b> Use ≥.</span><span><b>At most includes equality.</b> Use ≤.</span></div></section>
<section className="wn-section"><h3>AVORA Comparison-Symbol Method</h3><div className="lesson-rule"><span>1. Identify the two quantities.</span><span>2. Calculate first if either side contains an operation.</span><span>3. For whole numbers, compare from the highest place value.</span><span>4. For fractions, rewrite into a valid comparable form when needed.</span><span>5. For decimals, compare corresponding place values.</span><span>6. Decide the relationship.</span><span>7. Insert the correct symbol.</span><span>8. Read the statement from left to right to check its meaning.</span></div></section>
<section className="wn-section"><h3>Mastery Check</h3><ul><li>Explain =, ≠, &lt;, &gt;, ≤ and ≥.</li><li>Compare whole numbers, expressions, fractions and decimals.</li><li>Translate “at least” and “at most” correctly.</li><li>Arrange quantities in ascending and descending order.</li><li>Explain why a chosen comparison symbol is correct.</li></ul></section>
<div className="teacher-actions"><button type="button" className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}